### ISSUE TITLE
Latex template

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#1]

**Comment by kngoyal** [comment]
Added

**Comment by kngoyal** [comment]
I saw this in previous versions, can't find in the current one @vict0rsch

**Comment by vict0rsch** [comment]
I don't understand what you mean @kngoyal ?

**Comment by kngoyal** [comment]
Can you add the latex template ?

**Comment by vict0rsch** [comment]
Yeah the original idea was to generate it in the viz but I can add a static one
