### ISSUE TITLE
IntelPowerGadget path is incorrect 

### ISSUE THREAD

**Issue by LiamConnell** [mlco2/codecarbon#109]
* CodeCarbon version: 1.0.0
* Python version: Any
* Operating System: Windows

### Description

Per @DavidGRX:
> In core/cpu.py there is a path (for Windows) to an exe path that was not correct in my case. I understand Python but not the package installation and location, so I replicate my Intel Power directory with the expected name ""C:\Program Files\Intel\Power Gadget 3.5\PowerLog3.0.exe""

We should either clarify the documentation, or add another expected executable path to the python code.

**Comment by DavidGRX** [comment]
Great! 
additional information: running Windows 7 Professional, 64 bits. 
The Power Gadget for this version is 3.0.

**Comment by vict0rsch** [comment]
@LiamConnell  same, is this closed?

**Comment by LiamConnell** [comment]
@vict0rsch  This is not ready to close. To close we should have someone on a windows machine confirm that the documentation in the readme is accurate for the IntelPowerGadget installation and update if not. 

If the installation works without a problem I think its safe to assume this was user error

**Comment by vict0rsch** [comment]
OK cool I'll investigate asap
