### ISSUE TITLE
Linux RAPL files not present on AWS EC2 instances

### ISSUE THREAD

**Issue by LiamConnell** [mlco2/codecarbon#111]
* CodeCarbon version: 1.0.0
* Python version: Any 
* Operating System: Ubuntu 18.04, AWS Linux
        - They use Linux 4.15 and 4.14 respectively

### Description

I have tried to use the tool on two Linux OS's on AWS EC2 instances and it seems that the RAPL file is not found. `cpu.is_rapl_available()` returns `False`. I'm assuming that this is due to `sys/class/` not having a `powercap/` directory as specified in the codebase.

**Comment by LiamConnell** [comment]
I see two options for why `powercap/` is not in the system files. First is that RAPL powercap has been removed from a more recent Linux Version (it was introduced in 3.13 and I am testing in 4.14, 4.15). The second is that AWS EC2 instances are configured to not include this Linux tool. The second seems more likely. 

Some notes: 

[this](https://helda.helsinki.fi/bitstream/handle/10138/321707/RAPL_in_Action_Experiences_in_Using_RAPL_for_Power_Measurements.pdf?sequence=1) is a paper from Jan 2018 in which they claim to be able to measure power usage on EC2 using RAPL. Their exact methodology is not specified

[this](http://web.eece.maine.edu/~vweaver/projects/rapl/) is a University of Maine Professor who has done work with RAPL measurements several years ago. He describes three ways of accessing RAPL info: 
> * Reading the files under /sys/class/powercap/intel-rapl/intel-rapl:0 using the powercap interface. This requires no special permissions, and was introduced in Linux 3.13
> * Using the perf_event interface with Linux 3.14 or newer. This requires root or a paranoid less than 1 (as do all system wide measurements with -a) sudo perf stat -a -e "power/energy-cores/" /bin/ls Available events can be found via perf list or under /sys/bus/event_source/devices/power/events/
> * Using raw-access to the underlying MSRs under /dev/msr. This requires root.

The first option is what we currently have. I havent looked into the second option. The third option seems promising. There are some tools that monitor RAPL using MSR [here](https://github.com/kentcz/rapl-tools), [here](https://github.com/deater/uarch-configure) and [here](http://www.brendangregg.com/blog/2014-09-15/the-msrs-of-ec2.html). We could potentially integrate one of these into the `IntelRAPL` object, however it will require non-python code dependencies.

**Comment by LiamConnell** [comment]
@Lothiraldan would like to hear your opinion on this when you have a chance. I'm a bit out of my depth when it comes to things the linux kernel level (MSRs)

**Comment by Lothiraldan** [comment]
I doubt that we can do much better without having some help from the system. It is unlikely that we will be able to get a precise measure in virtualized environment like EC2.

**Comment by LiamConnell** [comment]
@Lothiraldan I think you're right for T2/3-like instances that are actually virtual units of compute that are shared. However, we might be able to cover other EC2 instance types. I believe most other instance types actually represent a box in a datacenter.

**Comment by LiamConnell** [comment]
For instance, [this](https://helda.helsinki.fi/bitstream/handle/10138/321707/RAPL_in_Action_Experiences_in_Using_RAPL_for_Power_Measurements.pdf?sequence=1) paper mentions them benchmarking on EC2 instances using RAPL (I assume without powercap). They dont go into details of the implementation unfortunately.

**Comment by gudiandian** [comment]
Hi, I am having trouble to use the tool on EC2 as well. Have you found out a solution? Thanks!

**Comment by benoit-cty** [comment]
Hi, We have started a PR to use the CPU load instead of RAPL : https://github.com/mlco2/codecarbon/pull/316

It will be nice if you could give it a try and let us know what you think.

**Comment by gudiandian** [comment]
> Hi, We have started a PR to use the CPU load instead of RAPL : #316
> 
> It will be nice if you could give it a try and let us know what you think.

Thank you so much for your reply! I think it is a good idea to use the CPU load for energy consumption estimation. I found that the CPU of the server that I am using (Intel(R) Xeon(R) Silver 4210R CPU @ 2.40GHz) is not included in the list of `codecarbon/data/hardware/cpu_power.csv`. The TDP of this CPU is 100W, so I added this information in `codecarbon/data/hardware/cpu_power.csv`. However, I found that the estimation of "All CPUs Power" is always 50W when I run different workloads, which I think is not accurate. Is there anything else that I should modify? Or the 50W is the most accurate estimation that we can have? Thank you!

**Comment by benoit-cty** [comment]
Yes, in case that RAPL is not available we use an approximation of 50% of the TDP, (ref https://github.com/mlco2/codecarbon/blob/e143d4a7d21fb8bb98aba8f28d040979d726063c/codecarbon/external/hardware.py#L24 )
Did you try with the branch _use-cpu-load_ ? And with a `pip install -e .` to be sure to use your local code and not the one from PyPi ?
