### ISSUE TITLE
Include accounting for TPUv2 and TPUv3

### ISSUE THREAD

**Issue by leondz** [mlco2/codecarbon#116]
Are power usages extracted and presented for TPUs / TPU pods?

**Comment by vict0rsch** [comment]
Hi, I'm sorry we did not gàt back to you on this.

We have not looked deeply into this topic but the first order approximation we made was it is hard to get live power usage. 

A workaround would be to use an average power usage for the duration of the job, assuming constant use of the accelerator.

We'll investigate!
