### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by LiamConnell** [mlco2/codecarbon#121]
### Description

When run inside of a container, CodeCarbon seems to be unable to access RAPL system files. This seems to be a solvable problem -- there is a RAPL-related docker image https://powerapi-ng.github.io/rapl.html

**Comment by vl4py** [comment]
@LiamConnell @tgll Just to be clear what kind of design would you rather see for this integration?
- a side-car approach calling publishing to the API?
- a in-app collection of power metrics ?
- Something else ?

**Comment by Lothiraldan** [comment]
Could someone try to run the `powerapi/rapl-formula` and see if it's able to extract something without needing the `--privileged` permission? Allowing a side-car RAPL container that would have the `--privileged` permission might be a good solution for security minded operations people that don't want to allow the main training container to run in privileged mode.

**Comment by LiamConnell** [comment]
> @LiamConnell @tgll @vict0rsch
> Just to be on the same page, what kind of design would you rather see for this integration?
> 
> * A side-car approach with calls publishing to the API?
> * A in-app collection of power metrics ?
> * Something else ?

1. I think the side-car approach sounds most promising, although I don't have experience doing anything like that. It also would need special consideration to keep with CC's design philosophy of simple integration. Perhaps some documentation with a docker-compose code snippet would suffice
2. The "fallback feature" makes this less of a priority in general since we get some data regardless of RAPL support

**Comment by vl4py** [comment]
> Could someone try to run the `powerapi/rapl-formula` and see if it's able to extract something without needing the `--privileged` permission? Allowing a side-car RAPL container that would have the `--privileged` permission might be a good solution for security minded operations people that don't want to allow the main training container to run in privileged mode.

@Lothiraldan I'll pair with @tgll. However, the documentation pushes to use `smartwatt-formula` rather than `rapl-formula`.  WDYT ?

**Comment by Lothiraldan** [comment]
@vl4py Let's try to find any docker image that can provide some data. I'm merely referenced `rapl-formula` because it was mentioned in https://powerapi-ng.github.io/rapl.html

**Comment by vl4py** [comment]
As power-api `hpwc-sensor` relies on `cgroup`, it cannot be used from macOSX. macOSX does not provide equivalent isolation guarantees as LXC. 

So we are losing part of our target users for local usage. I'll keep going on my test for linux-based OS since the side-car approach still makes sense when working for remote servers docker. 

FYI @vict0rsch
