### ISSUE TITLE
CarbonBoard Refactor: Frontend-backend model – REST API for custom frontend extensions

### ISSUE THREAD

**Issue by LiamConnell** [mlco2/codecarbon#123]
### Description

REST API for custom frontend extensions

**Comment by jonnyliu15** [comment]
Hi, I'd like to take this on. Is there a better way to get in contact with the team so I can hash out requirements?

**Comment by vl4py** [comment]
> Hi, I'd like to take this on. Is there a better way to get in contact with the team so I can hash out requirements?

@vict0rsch slack or anything else?

**Comment by vict0rsch** [comment]
Hey @jonnyliu15 I'm sorry I missed your message. Are you willing to join us and chat through slack about how things are evolving?

**Comment by benoit-cty** [comment]
Done in https://github.com/mlco2/codecarbon/pull/145
