### ISSUE TITLE
Make usage of Sphinx autodoc to avoid to manually copy params and their docstring

### ISSUE THREAD

**Issue by Lothiraldan** [mlco2/codecarbon#130]
The docs currently duplicate the docstrings of the public objects in https://github.com/mlco2/codecarbon/blob/master/docs/edit/parameters.rst. 

We could use https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html to avoid doing such duplication.

**Comment by benoit-cty** [comment]
A reading that may be interesting : https://realpython.com/documenting-python-code/

**Comment by SaboniAmine** [comment]
I'm closing this, as a bit outdate. Please re-open if needed
