### ISSUE TITLE
Fallback power estimation constants

### ISSUE THREAD

**Issue by LiamConnell** [mlco2/codecarbon#131]
Cloud providers do not allow access to hardware interfaces like RAPL. We can provide a workaround by setting a default power measurement constant (in kW) for `EmissionsTracker._measure_power()`, or a default `Hardware` object to add to `EmissionsTracker._hardware` if empty. 

There could be various levels of constant maps to fallback on. For instance, a constant per processor model. If not found, then a constant per type of processor (CPU/GPU).

**Comment by benoit-cty** [comment]
What will be the improvement with `POWER_CONSTANT = 85` in hardware.py ?
