### ISSUE TITLE
Add context manager

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#137]
Would be nice to be able to do something like 

```python
with EmissionsTracker() as tracker:
	...
```

**Comment by sanders41** [comment]
Do you have an idea how you would like this to work? It looks like the cleanup the context manager would need to run is the [stop method](https://github.com/mlco2/codecarbon/blob/08635e5184761bd6cd632527d4891a601dcc2f72/codecarbon/emissions_tracker.py#L184-L205), but the return value from this method is needed so I'm not sure how you could use a context manger. Or maybe I'm wrong and something else needs to be run for the cleanup?

**Comment by vict0rsch** [comment]
Hey @sanders41 thanks for pitching in! 

A few ideas:

* we don't need the return value: iut has been written to a file or pushed to a http endpoint
* if we wanted to keep this possibility looks like (2 mins of googling so there may be a better way) the easiest would be to store that return value as an attribute to the Tracker, something like:
    ```
	self.final_emissions = emissions_data.emissions
    return emissions_data.emissions
    ```

**Comment by SaboniAmine** [comment]
This return value looks fine to me, as it can be used to check the state of the emissions tracking outside out the context. 
From the API side any acknowledgement of run completeness would be a useful information, so maybe a call to something like '/run/report/'  could be made in the stop method, if the run is remotely tracked?

**Comment by vict0rsch** [comment]
report would be what, a summary?

**Comment by SaboniAmine** [comment]
I still am unsure about its responsibility.

My guess is that this report could ensure : 
- out() have been performed correctly all along the run. For distant output (/run/report) that could mean sending a 'stop_run' message / total number of data points. If there is a discrepancy, the context manager state could be useful to resolve it. Locally, the implementation seems already fine to me.
- Total energy / emissions value is coherent. The stop method could also be used to filter/correct outlier values before saving outputs. This will involve the loss of data points but avoid to compute incoherent aggregations (as it could have been with this example run, the total sum would be pretty incoherent)

![image](https://user-images.githubusercontent.com/43726203/121766864-2a768080-cb55-11eb-961b-0a954519577d.png)
