### ISSUE TITLE
TODO: setup github actions on the `api` branch

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#143]
I think we need to have actions set up so that we can also check for commits/pushes on the `api` branch. Thoughts?

**Comment by benoit-cty** [comment]
Github Actions has a solution for that : https://medium.com/@SammyRulez/git-monorepos-with-github-actions-e47f56d8793b
We could build a specific action file for the api folder.

**Comment by SaboniAmine** [comment]
Should the behavior be the same as for master ? (Pre-commit / Package / Test)
Could we insert an integration test between package / api ?

To locally test pipelines, [act](https://github.com/nektos/act) is quite useful.
