### ISSUE TITLE
Codecarbon Database Schema

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#159]
By @alencon :

![](https://user-images.githubusercontent.com/56264647/116627673-dff6c700-a94d-11eb-9493-8bd62bc32b80.jpg)

**Comment by vict0rsch** [comment]
I think @Lothiraldan could help with his XP at comet, can you share the dependency structure you have user/project/workspace? I'm not sure I'm clear on what's happening :p 

Another source of inspiration is Github: you have users, which can have projects (=repo) of their own and share such projects with a team (=contributors) without necessarily being parts of organizations. But they can create an org if they want to. 

So let's discuss this:

* Emission <-> Experiment: **many to one**: many emissions are associated with exactly one exp
* Experiment <-> Project : **many to one**: many exps are associated with exactly one project
* Experiment <-> User: **many to one**: many exps are associated with exactly one user (within a project with multiple contributors you need to be able to identify which exp was done by which user)
* Project <-> Team: **one to many** a project belongs to a single team but a team can have multiple projects
* Team <-> User: **many to many** a user can be part of multiple teams which can have multiple users
* Team <-> Org: **one to many** a team belongs to a single org but an org can have multiple teams

**Comment by benoit-cty** [comment]
Hello,
Discussing with @SaboniAmine and @alencon we will add a "run" level, between Emission and Experiment, like in ML Flow.
The "run" will be dynamically created.

**Comment by Lothiraldan** [comment]
I can discuss how our namespaces are structured. Each `comet_ml.Experiment` have an unique ID, generated on the client side (with uuid.uuid4() basically). Each experiment uses a single API Key attached to a single user. Each user has a default workspace (named after the user) and inside that workspace there is a default (private) project named `general`. That means when sending data (and if the user don't provides a workspace or project_name), we can find "where" to store the data.

Users can also provide a workspace name and/or a project name. If the workspace exists and if the user has permission to write in it, we store the data in the provided workspace and/or project.

Projects (and experiment) are automatically created but workspaces are not. Permission are managed at the workspace level and each workspace admin can add other members to read and/or write to that workspace.

Namespaces (or team/project/organizations) design often comes to solves permissions requirements, how are you envisioning read/write permissions?

**Comment by vict0rsch** [comment]
TODO: add os field in run

**Comment by benoit-cty** [comment]
The schema is there : https://github.com/mlco2/codecarbon/blob/master/carbonserver/Images/CodecarbonDB.jpg
