### ISSUE TITLE
Prometheus for emissions monitoring

### ISSUE THREAD

**Issue by SaboniAmine** [mlco2/codecarbon#162]
We had an interesting chat yesterday with @benoit-cty, about the publication of Code Carbon metrics to a prometheus instance. Here are some of our thoughts:

The idea have already been discussed, and Benoît Petit from Boavizta / Hubble presented us his usage of Prometheus in Scaphandre, [an interesting use case](https://data-for-good.slack.com/archives/C01T191L5FS/p1619938142108400).

The prometheus test might be quite easy to define / implement on a NVIDIA GPU, as its monitoring interface seems quite easy to use. We had a quick exploration with Benoît and found interesting data using the CLI, which may be quite easy to push to a prometheus instance:
```bash
# Retrieves for accounted apps gpu utilization percentage
nvidia-smi --query-accounted-apps=gpu_name,pid,gpu_utilization,time --format=csv

# Retrieves for each gpu card the current power consumption, which can be ratio'd by the app percentage 
nvidia-smi
```

Prometheus server can be deployed in a [docker image](https://prometheus.io/docs/prometheus/latest/installation/) and used in 2 modes :
- configured to pull metrics from a [bash agent](https://github.com/prometheus/node_exporter) (or a Kubernetes cluster, with the NVIDIA[ data center management exporter](https://github.com/NVIDIA/gpu-monitoring-tools#dcgm-exporter))
- receiving push requests from applications. This can be used in the CC package, with a light http client regularly pushing data to the [server](https://github.com/prometheus/client_python#exporting-to-a-pushgateway).

What do you think ?

**Comment by benoit-cty** [comment]
The name of 'NVIDIA data center management exporter' is misleading. It could be use on any computer with docker.
The case we propose with Amine is to :
- deploy Prometheus with docker on a server.
- Then use Prometheus Node Exporter on a computer with nvidia exporter to push data to Prometheus.
- use code carbon on the same computer and compare the results.

**Comment by inimaz** [comment]
> receiving push requests from applications. This can be used in the CC package, with a light http client regularly pushing data to the [server](https://github.com/prometheus/client_python#exporting-to-a-pushgateway).

I would like to give this a go, if that's ok.
I will start by adding a pushgateway mode where on top of logging to a file/console, codecarbon can log the emissions to prometheus.

**Comment by jennydaman** [comment]
I would like to have CodeCarbon in a Kubernetes DaemonSet running `codecarbon monitor` and pushing data to Prometheus.

These days I am too busy to contribute but it's something I might try in the future.

**Comment by benoit-cty** [comment]
Hello, it wiil work if you allow the DaemonSet to access RAPL files on the host.

I close this issue because Prometheus exporter has been delivered in https://github.com/mlco2/codecarbon/pull/395
