### ISSUE TITLE
Deploy to Clever Cloud

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#169]
How we would deploy to Clever Cloud ?

What do we need :
- PostgreSQL DB (size ?)
- Python FastAPI (size ?)
- Superset ( https://www.clever-cloud.com/blog/engineering/2021/05/04/how-to-deploy-apache-superset-on-clever-cloud/ )

**Comment by SaboniAmine** [comment]
That should be enough for a first version, if we can test the deployed API with the swagger documentation & pgadmin for the database, it should be enough to make superset available. The current front integration could be a next step.

It doesn't seem that we can have free instances for the API (as I thought), but we could start with a nano, and a pico instance for the database.

For the CD, we could manually deploy each components, and then script each action with the clever cli.
That could be a first step to make it deployable using Github Actions, as Clever Cloud doesn't seem to support docker compose / direct ssh to deploy.
The [configuration provider](https://www.clever-cloud.com/doc/deploy/addon/config-provider/) might also be useful.
