### ISSUE TITLE
Recipe on conda-forge

### ISSUE THREAD

**Issue by PertuyF** [mlco2/codecarbon#171]
Dear CodeCarbon team,

Thank you very much for the effort you're putting into developing `codecarbon`. I love the idea!
I submitted a [conda recipe for conda-forge](https://github.com/conda-forge/staged-recipes/pull/13434), based on your PyPi package. It will benefit from their CI/CD infrastructure with automatic (or semi-auto) version bump while you update the PyPi version of the package. This could alleviate the effort you have to put into maintaining your own conda package and channel.
If you are interested into being maintainers of this recipe, please tell me and I'll add you before closing the submission.

Best,
Fabien

**Comment by benoit-cty** [comment]
Thanks for your contribution, the last version of CodeCarbon has been published using your work:
https://anaconda.org/conda-forge/codecarbon
