### ISSUE TITLE
Support AMD CPU

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#178]
* CodeCarbon version: 1.2.0
* Python version: 3.8
* Operating System: Ubuntu 20.04

### Description

Use codecarbon on a computing powered by AMD Ryzen Threadripper.

### What I Did

```
python examples/do_nothing.py 
[...]
CODECARBON : Intel RAPL files not found at /sys/class/powercap/intel-rapl on linux
```

### What we ca do

Have a look at https://github.com/ocerman/zenpower but it is a kernel driver, so not the easiest solution for end users !

**Comment by vict0rsch** [comment]
Closing for now, if someone wants to make CC compatible with AMD CPUs, please re-open and help us out :)

**Comment by benoit-cty** [comment]
AMD CPU is now supported by Intel RAPL, so Code Carbon support them !
