### ISSUE TITLE
Use the same data model in package and API

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#181]
* CodeCarbon version: 1.2
* Python version: 3.8
* Operating System: Linux

### Description
The ApiClient class use a dataclasses model, but the API use a pyDantic BaseModel. It will be nice to share the same file.
As proposed by @SaboniAmine :
`To avoid duplications, we could import carbonserver.api.schemas classes and re-export them here under the right class name. One way to do it could be to export them as a partial package, something like carbonserver[types]`

**Comment by vict0rsch** [comment]
Close @benoit-cty ?

**Comment by benoit-cty** [comment]
We have not done it and I think it will be mandatory for https://github.com/mlco2/codecarbon/issues/246 to ensure the JSON are compliant with the API format.

**Comment by SaboniAmine** [comment]
Closing this as an ongoing work should validate this issue. Please re-open if needed
