### ISSUE TITLE
[Problem] track_emissions decorator returns a None

### ISSUE THREAD

**Issue by julien-boulay** [mlco2/codecarbon#182]
* CodeCarbon version: 1.2.0
* Python version: 3.7
* Operating System: MacOS

### Description
Hi,
I encountered a problem with the track_emissions decorator. 
While trying to wrap the training function of my model, which has the particularity to return a result (an element of a "Model" class needed for my use case), I realized that the track_emissions decorator was forcing a None return.

The problem (if it is one) seems to come from the track_emissions function : 
https://github.com/mlco2/codecarbon/blob/c284dc58f6e3378b01e5364e6cfed6eada369659/codecarbon/emissions_tracker.py#L415

line 478 and line 489
https://github.com/mlco2/codecarbon/blob/c284dc58f6e3378b01e5364e6cfed6eada369659/codecarbon/emissions_tracker.py#L478
https://github.com/mlco2/codecarbon/blob/c284dc58f6e3378b01e5364e6cfed6eada369659/codecarbon/emissions_tracker.py#L489

store the return of fn : 

`return_fn = fn(*args, **kwargs)`

and then add 

`return return_fn`
in https://github.com/mlco2/codecarbon/blob/c284dc58f6e3378b01e5364e6cfed6eada369659/codecarbon/emissions_tracker.py#L460

Thank you !
Julien

**Comment by benoit-cty** [comment]
Thanks, I've done it in #236
