### ISSUE TITLE
Better storage of results

### ISSUE THREAD

**Issue by cifkao** [mlco2/codecarbon#183]
In my opinion, saving the emissions to a CSV file is not a good choice for at least two reasons:
1. It is not easily possible to update the results periodically (as opposed to once at the end of the run) as suggested in #66. (If results are only written at the end, it can easily happen that the experiment gets killed abruptly and doesn't have the chance to save the result.)
2. Problems arise when running experiments on different machines without shared storage. When copying the experiment results back to a central location, the emission information either gets overwritten or needs to be merged by hand.

One alternative is saving the emissions of each run in a separate file with a unique filename. This would prevent both of the problems I described.

**Comment by vict0rsch** [comment]
Thank you for your suggestion. We're working on creating an API to store results online in a protected database so those problems should disappear soon :)

**Comment by benoit-cty** [comment]
Ca we close this issue ?
