### ISSUE TITLE
Issue in units? CPU vs GPU

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#184]
Extract of a log:
```
[codecarbon INFO @ 22:37:12] GPU Power Consumption : Power(kW=0.390005)
[codecarbon INFO @ 22:37:12] Energy consumed GPU : Energy(kwh=0.11006903808049802)
[codecarbon INFO @ 22:37:12] CPU Power Consumption : Power(kW=0.0425)
[codecarbon INFO @ 22:37:12] Energy consumed CPU : Energy(kwh=0.1114854821467378)
```
The Power is not the same but the energy is quite the same.

**Comment by benoit-cty** [comment]
These data come from a computer running an AMD Ryzen Threadripper 1950X, so codecarbon use a constant estimator : https://github.com/mlco2/codecarbon/blob/b22ca0e698a8596ac4b36a0531ee672953986954/codecarbon/core/cpu.py#L232
and https://github.com/mlco2/codecarbon/blob/b22ca0e698a8596ac4b36a0531ee672953986954/codecarbon/emissions_tracker.py#L153

The power is estimated by self._tdp * CONSUMPTION_PERCENTAGE_CONSTANT ( https://github.com/mlco2/codecarbon/blob/b22ca0e698a8596ac4b36a0531ee672953986954/codecarbon/external/hardware.py#L88 )

CONSUMPTION_PERCENTAGE_CONSTANT is 0.5

The TDP come from https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/hardware/cpu_power.csv where we can read 180W for this CPU.

So power = 180 * 0.5 = 90W = 0.09 kW

**Comment by benoit-cty** [comment]
First problem: the CPU was not detected because his name was `AMD Ryzen Threadripper 1950X 16-Core Processor` and we have only `AMD Ryzen Threadripper 1950X` in the database.
So here is the patch to handle all AMD Threadripper :
```
splitted = model.split(' ')
        if splitted[2]  == 'Threadripper' and len(splitted) == 6:
            model = splitted[0] + ' ' + splitted[1] + ' ' + splitted[2] + ' ' + splitted[3]
        return model
```
After that, we have our 0.09 kW:
`Energy consumed for CPU : Energy(kwh=0.0005626940578272056)=Power(kW=0.09) power x Time(seconds=14.965599060058594)`

**Comment by vict0rsch** [comment]
You're right it's a cumulative sum: 

```
for each time_interval: for each hardware: total_energy += time_interval * hardware.power
```

But it's still an energy quantity so it's `kWh` 

So we should log `time_interval * hardware.power` for each hardware and finally something like 

```
Total energy so far: {self._total_energy}
```

**Comment by vict0rsch** [comment]
However the first log should be true, is it the case? Did you show the first one? In that case something's wrong we should have `total_energy == time_interval * hardware.power`

**Comment by benoit-cty** [comment]
For the CPU matching it will be nice if someone could use  https://www.datacamp.com/community/tutorials/fuzzy-string-python to do the match instead of the strict string equality.

**Comment by benoit-cty** [comment]
Closed as there is no issue in unit.
