### ISSUE TITLE
Discrepancy in energy estomates between code-carbon and experiment-impact-tracker

### ISSUE THREAD

**Issue by nikhil153** [mlco2/codecarbon#188]
* CodeCarbon version: 1.2.0 (pip install)
* Python version: 3.7.9
* Operating System: Ubuntu 18.04
* Proc: Intel® Core™ i7-8650U CPU @ 1.90GHz × 8 

### Description

Hi,

This is a wonderful tool and I especially like the visualization apps. 

At the moment, I am comparing results from [experiment-impact-tracker](https://github.com/Breakend/experiment-impact-tracker) with code-carbon and I am seeing big differences (1000x) in the energy estimates with default configs. I believe both of these tools use RAPL to track CPU power draws and report in kilo-watt-hours. I know there are some differences in the two approaches (e.g. PUE usage), nevertheless it shouldn't cause such large difference. 

### What I Did
I ran a modified version of [example code](https://github.com/Breakend/experiment-impact-tracker/blob/master/examples/my_experiment.py) for this comparison.The code is below: 

```
import sys
import tempfile
import torch
import pandas as pd
import numpy as np

sys.path.append('../../experiment-impact-tracker/')

from experiment_impact_tracker.compute_tracker import ImpactTracker
from experiment_impact_tracker.data_interface import DataInterface

from codecarbon import EmissionsTracker, OfflineEmissionsTracker

import logging
logging.basicConfig(level="DEBUG")

class Experiment:
    def __init__(self):
        device = torch.device("cpu")

        # N is batch size; D_in is input dimension;
        # H is hidden dimension; D_out is output dimension.
        N, D_in, H, D_out = 1024, 10000, 1000, 100

        # Create random input and output data
        self.x = torch.randn(N, D_in, device=device)
        self.y = torch.randn(N, D_out, device=device)

        # Randomly initialize weights
        self.w1 = torch.randn(D_in, H, device=device)
        self.w2 = torch.randn(H, D_out, device=device)
        self.learning_rate = 1e-6

    def train(self):
        # Forward pass: compute predicted y
        h = self.x.mm(self.w1)
        h_relu = h.clamp(min=0)
        y_pred = h_relu.mm(self.w2)

        # Compute and print loss; loss is a scalar, and is stored in a PyTorch Tensor
        # of shape (); we can get its value as a Python number with loss.item().
        loss = (y_pred - self.y).pow(2).sum()

        # Backprop to compute gradients of w1 and w2 with respect to loss
        grad_y_pred = 2.0 * (y_pred - self.y)
        grad_w2 = h_relu.t().mm(grad_y_pred)
        grad_h_relu = grad_y_pred.mm(self.w2.t())
        grad_h = grad_h_relu.clone()
        grad_h[h < 0] = 0
        grad_w1 = self.x.t().mm(grad_h)

        # Update weights using gradient descent
        self.w1 -= self.learning_rate * grad_w1
        self.w2 -= self.learning_rate * grad_w2


def my_experiment(log_dir, n_steps=100) -> None:

    ## code-carbon tracker
    tracker_CC = EmissionsTracker(output_dir=log_dir) #measure_power_secs=1 (also tried)
    tracker_CC.start()

    ## exp-impact-tracker
    tracker = ImpactTracker(log_dir)
    tracker.launch_impact_monitor()

    exp = Experiment()

    for t in range(n_steps):
        if t % (n_steps//10) == 0:
            print(f"Pass: {t}")
            # Optional. Adding this will ensure that your experiment stops if impact tracker throws an exception and exit.
            tracker.get_latest_info_and_check_for_errors()
        exp.train()

    tracker_CC.stop()
    print(f"Please find your experiment logs in: {log_dir}")


if __name__ == "__main__":

    log_dir = tempfile.mkdtemp()
    n_steps = 1000

    my_experiment(log_dir, n_steps=n_steps)

    # exp-impact-tracker logs
    data_interface1 = DataInterface([log_dir])
    exp_impact_tracker_power = data_interface1.total_power
    exp_impact_tracker_duration = data_interface1.exp_len_hours * 3600

    # code-carbon logs
    cc_df = pd.read_csv(f'{log_dir}/emissions.csv')
    cc_duration = cc_df['duration'].values[0]
    cc_energy_consumed = cc_df['energy_consumed'].values[0]

    print(f'runtimes (sec) exp-impact-tracker: {exp_impact_tracker_duration}, code-carbon: {cc_duration}')
    print(f'total power from exp-impact-tracker: {exp_impact_tracker_power}\nenergy consumed from code-carbon: {cc_energy_consumed}')

```
The output: 
```
runtimes (sec) exp-impact-tracker: 273.8940119743347, code-carbon: 279.569203

total power from exp-impact-tracker: 0.0012712099637642393
energy consumed from code-carbon: 1.2468294944596514e-06
```
Curious to know what's causing this! Thanks so much!

**Comment by benoit-cty** [comment]
Hello,
Thanks for using CodeCarbon !
Could you please post your emissions.csv ?
And maybe run it again with debug log ?

You run your code for almost 5 hours and the TDP of your CPU is 15W, so I will have expected a power usage of 0.07 kWh but both result is far below.

FYI we will soon release an API server to monitor the energy during the run if you have an internet access.

**Comment by vict0rsch** [comment]
Sorry for the time it took us to notice your issue, thank you for reporting. As @benoit-cty mentioned having the logs would help us debug with you :)

**Comment by vict0rsch** [comment]
* If the tracking mode is RAPL then we'd need to check your RAPL files @nikhil153 to make sure we can read them right. To help, can you tell us if 1/ `/sys/class/powercap/intel-rapl` exists, what's in it and the content of files called `energy_uj` 2/ if `codecarbon` logs anything in debug mode.

* If the tracking mode is TDP and the CPU is found then I would expect 

  ```
  279s * 1/3600 = 0.0775h * 15W = 1.1625 Wh * CONSUMPTION_CONSTANT(=0.5) = 0.58125 Wh = 0.00058125 kWh
  ```
  
  This is an approximation of what should be reported. But it seems to be reported by neither package (but we'd be off by 3 orders of magnitude)
  
* If the tracking mode is TDP but the CPU is not found I would expect

	```
	0.0775h * POWER_CONSTANT(=85W) = 6.5875W * 0.5 = 3.29375W = 0.00329375 kWh
	```
	
	And we'd still be off by orders of magnitude...

**Comment by nikhil153** [comment]
Thanks for getting back to me @benoit-cty and @vict0rsch! 

I just ran the test again (runtime ~5mins) and here are the outputs
1) codecarbon.log (single line):
```
2021-06-29 14:16:38,677 - codecarbon  : INFO     Tracking Intel CPU via RAPL interface
```
2) emissions.csv:
```
timestamp,project_name,duration,emissions,energy_consumed,country_name,country_iso_code,region,on_cloud,cloud_provider,cloud_region
2021-06-29T14:20:37,codecarbon,238.37492489814758,4.730177614631637e-08,1.1976209153476881e-06,Canada,CAN,ontario,N,,
```
In comparison the experiment-impact-tracker estimates:
total power from exp-impact-tracker: 0.0012955583743692652

Additionally, I tried [another tracker](https://github.com/lfwa/carbontracker) to see if exp-impact-tracker is the one overestimating power draws, but the results from the 3rd tracker are similar to the experiment-impact-tracker:
CarbonTracker estimate:  {'epochs': 1001, 'duration (s)': 230.0, 'energy (kWh)': 0.0016785649, ... } 

Let me know if I can provide any additional info. Thanks again!

**Comment by nikhil153** [comment]
Here is a screenshot of /sys/class/powercap/intel-rapl dir and content of energy_uj files:

![image](https://user-images.githubusercontent.com/7978607/123850064-8c6e0e80-d8e7-11eb-81c2-97a26df12ccd.png)

Also the codecarbon log does not contain any debug messages.

**Comment by vict0rsch** [comment]
@nikhil153 thanks for sharing this and reporting back.

I think I found the culprit!! 

```python
    def end(self, delay):
        self.power_measurement = (
            abs(float(self._get_value()) - float(self.energy_reading))
            / Time.from_seconds(delay).hours
        )
        return
```

should be 

```python
    def end(self, delay):
        self.power_measurement = (
            abs(float(self._get_value()) - float(self.energy_reading))
            / delay # here!
        )
        return
```

Because power (W) is in J/s not J/h! So here's our 1/3600 discrepancy. (Right?)

**Comment by nikhil153** [comment]
@vict0rsch, Cool! I think it makes sense - assuming delay is measured in seconds! I guess these units get a bit confusing because in the end we usually report Watt-hours as the gross energy consumption.

**Comment by vict0rsch** [comment]
Closing ; thank you for your help and concern :)

**Comment by nikhil153** [comment]
Thanks for the prompt response! Out of curiosity and to understand your implementation better - are there any key differences in the motivation and the approach for developing CodeCarbon compared to the experiment-impact-tracker? Both of these projects seem to have contributors from Montreal / Mila! I too am currently working at McGill trying to benchmark several neuroimaging tools with these trackers and so I want to understand these approached better!

**Comment by vict0rsch** [comment]
Good to know! I can't say there's a fundamental difference in spirit, it's initially just parallel efforts and I was not aware they were working on it until they published. Now I think CodeCarbon is moving in a slightly different direction, using an online API+Database to store and aggregate results over a potentially long period and several people

**Comment by nikhil153** [comment]
Thanks for the clarification. Online API+Database would be a great addition! I am part of a [Sustainability working group](https://neuropipelines.github.io/index) in a Neuroimaging community ([OHBM](https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=3267)). We have been looking for a web-tool to contribute and publish our benchmarking efforts. So I will keep following CodeCarbon's progress!

**Comment by benoit-cty** [comment]
The API+Database is now available in master but not yet in the PyPi package, let me now if you want to use it.

**Comment by nikhil153** [comment]
@benoit-cty - yes, I would love to try out the API. I believe I need a key? I couldn't find the details on how to obtain one on https://codecarbon.io.

**Comment by benoit-cty** [comment]
Well, we don't check API key yet, so you don't need one ;)
You have to pull master. Then do :
`pip install --editable . --upgrade`
`codecarbon init`
This will get you a experiment_id and put it in a config file.
(have a look to https://github.com/mlco2/codecarbon/pull/202 for more detail)
Then you could add `save_to_api=True,` in your existing decorator.
If something goes wrong, try https://github.com/mlco2/codecarbon/blob/master/examples/api_call_debug.py and send the output.
You could query the API from https://api.codecarbon.io/docs
A dashboard is coming...
