### ISSUE TITLE
Separate CPU and GPU consumption in emissions output

### ISSUE THREAD

**Issue by Minervabooks** [mlco2/codecarbon#195]
* CodeCarbon version: 1.2.0
* Python version: 3.6
* Operating System: MAC

### Description

At the moment total energy contains the sum of all energy consumed by the CPU and GPU and it's the only measure that exist in the output results. It would be best to store the CPU and GPU consumption separately as well.

**Comment by Minervabooks** [comment]
I have couple of questions around this:

1. I have added 2 measures called cpu_power and gpu_power in the package inside`emission_tracker` . Should they be in Kwh as well? (Also, let me know if the naming is good)

**Comment by benoit-cty** [comment]
Looks good to me. We may rename in '.bak' the existing file if in wrong format ?

**Comment by vict0rsch** [comment]
To me too :) 

WRT 2. I think we could create a new one? Or rename the previous one?

**Comment by vict0rsch** [comment]
As we're adding sources of information, maybe it would be worth having `self._total_power` as a dictionary? And then have something like `total_power = sum(self._total_power.values())`
