### ISSUE TITLE
Energy mix derived from eGrid2016

### ISSUE THREAD

**Issue by ngoterence** [mlco2/codecarbon#206]
Hi, I have trouble figuring out how you deduced the energy mix of different countries (for private infrastructure, in global_energy_mix.json) based on eGrid2016, which only contains US data. On your website :

"We derive the international energy mixes from the most recent year available in the United States’ Energy Information Administration’s Emissions & Generation Resource Integrated Database (eGRID; 2016). We approximate the energy mixes by examining the share of total primary energy produced and consumed for each country in the dataset and determining the proportion of energy derived from fossil fuel and low-carbon sources.".

Could you provide further details please ? I am actually trying to use electricitymap data with CodeCarbon, but I would like to have a better understanding of the current data first. Thanks !

**Comment by benoit-cty** [comment]
Hi, the global energy mix came from the Electricity Map team.
You could also use [CO2 Signal](https://api.co2signal.com), wich is an API of Electricity Map.

**Comment by ngoterence** [comment]
@benoit-cty thanks for your reply ! Ok so I suppose the explanation from Methodology section on CodeCarbon website is no longer relevant ? 
What about eGrid then, have you totally stopped using it for global_mix_energy ?
And do you know why CodeCarbon don't leverage real time data from Electricitymap ? To me, it seems that it is one of its biggest strength.

**Comment by benoit-cty** [comment]
Yes, real time will be perfect for us, but unfortunately there is no free API for that. CodeCarbon user's have to register to ElectricityMap /  CO2 Signal to get a co2_signal_api_token.
Maybe @vict0rsch had a better answer ?

**Comment by vict0rsch** [comment]
That's right, we use a mix of Electricity Map / eGrid (we should update the Methodology indeed) for static data. 

IFF you have registered for https://co2signal.com/ (same team as EM) you can pass a token to CodeCarbon and we'll ping the API for live data :)

**Comment by ngoterence** [comment]
Got it @benoit-cty @vict0rsch thank you ! May I have more information about the way Electricity Map & eGrid data are used please ? 
Looks like Electricitymap provides electric mix whereas the values of global_mix_energy correspond to energy mix (from what I've seen for France)

**Comment by benoit-cty** [comment]
Sorry for late answer. Yes, Electricity Map and CO2 Signal provide carbon intensity : we just have to multiply it with measured power.
For global_mix_energy we have a problem as stated in https://github.com/mlco2/codecarbon/issues/211 : it is the energy mix of the whole country, not the electricity mix.
