### ISSUE TITLE
Conversion of energy and power values of Intel_RAPL 

### ISSUE THREAD

**Issue by hassenebyy** [mlco2/codecarbon#212]
Hi everyone,
I pursued the conversion steps of the CPU consumption withe intel RAPL in codecarbon and I found some incoherant conversions.

1- First issue is in the function end() in RAPL.py : 
The value of start() and get_value is in Kwh. The subtraction still in kWh. But when you divide by delay (in seconds), we must have kWh/s right ?
At that point I suggest to convert delay to hours to obtain power measurement value in KiloWATT.

`    def end(self, delay):
        self.power_measurement = (
            abs(float(self._get_value()) - float(self.energy_reading)) / delay
        )
        return `
**replace delay by (delay/3600)**

2- Second issue is in hardware.py, class CPU() function get_power_from_CPUs: 
As we see, we have values in Kwh/s. The return of this function is converted to kiloWATT as if the value power was in WATTS. I think that this is not really correct.
I suggest to delete the conversion at this return and return power.

```
    def _get_power_from_cpus(self) -> Power:
        """
        Get CPU power from Intel Power Gadget
        :return: power in kW
        """
        if self._mode == "constant":
            power = self._tdp * CONSUMPTION_PERCENTAGE_CONSTANT
            return Power.from_watts(power)

        all_cpu_details: Dict = self._intel_interface.get_cpu_details()

        power = 0
        for metric, value in all_cpu_details.items():
            if re.match(r"^Processor Power_\d+\(Watt\)$", metric):
                power += value
        return Power.from_watts(power)`
```

**replace by return power**

Please find enclosed a schemas to help understand the issue.

Thanks for your time,

Hassene

<img width="825" alt="issues carbon" src="https://user-images.githubusercontent.com/37904140/126187127-1e9b9351-5625-488e-b243-351dcf036924.png">

**Comment by vict0rsch** [comment]
Hi @hassenebyy !

Thank you for your remarks and putting such an effort in helping out!

1) This is very true there's a confusion between `J = W * s` and `kWh = kW * h` check out #214 

2) I don't agree (or don't understand the issue), see `# >>>` hereafter:

```
    def _get_power_from_cpus(self) -> Power:
        """
        Get CPU power from Intel Power Gadget
        :return: power in kW
        """
        if self._mode == "constant":
			# >>> _tdp is in W
			# >>> CONSUMPTION_PERCENTAGE_CONSTANT has no unit
			# >>> so power is in W
            power = self._tdp * CONSUMPTION_PERCENTAGE_CONSTANT
			# >>> we want kW so Power.from_watts(power) makes sense
            return Power.from_watts(power)

        all_cpu_details: Dict = self._intel_interface.get_cpu_details()

        power = 0
        for metric, value in all_cpu_details.items():
            if re.match(r"^Processor Power_\d+\(Watt\)$", metric):
				# >>> value is in W so power is in W
                power += value
		# >>> we want kW so Power.from_watts(power) makes sense
        return Power.from_watts(power)
```

**Comment by hassenebyy** [comment]
Thank you for your return.
For the second issue, I might be confused. Here's what I intended to say : 

Using `Power.from_Watts(power)` converts watts to kilowatts right ?

Then if we had in RAPL.py at the end() function a returning value in KW. So in `get_cpu_details()`, the returning values of the power will be in KW.

In this case, why you convert the returning value of the variable **POWER** in `_get_power_from_cpus(self)` to Kilowatts while it's already the case ?  
If I understood the steps, when you do `return Power.from_Watts(power)` , the returned value is in Mwh.


`    all_cpu_details: Dict = self._intel_interface.get_cpu_details()

    power = 0
    for metric, value in all_cpu_details.items():
        if re.match(r"^Processor Power_\d+\(Watt\)$", metric):
			# >>> value is in W so power is in W
            power += value
	# >>> we want kW so Power.from_watts(power) makes sense. // Here the power value seems to be in KW.
    return Power.from_watts(power).  // This value would be in Mwh or not ?` 

I am sorry if I am not so good in explanations.

Regards.
