### ISSUE TITLE
Could not measure RAM Power ([Errno 12] Cannot allocate memory)

### ISSUE THREAD

**Issue by stas00** [mlco2/codecarbon#242]
Splitting off from https://github.com/mlco2/codecarbon/issues/238 as it is somewhat different:

I'm now testing the latest version on the live multi-node HPC setup and during the startup I now see:
```
[codecarbon WARNING @ 23:27:15] Could not measure RAM Power ([Errno 12] Cannot allocate memory)
WARNING:codecarbon:Could not measure RAM Power ([Errno 12] Cannot allocate memory)
[codecarbon WARNING @ 23:27:16] Could not measure RAM Power ([Errno 12] Cannot allocate memory)
WARNING:codecarbon:Could not measure RAM Power ([Errno 12] Cannot allocate memory)
[codecarbon WARNING @ 23:27:16] Could not measure RAM Power ([Errno 12] Cannot allocate memory)
WARNING:codecarbon:Could not measure RAM Power ([Errno 12] Cannot allocate memory)
[codecarbon WARNING @ 23:27:16] Could not measure RAM Power ([Errno 12] Cannot allocate memory)
WARNING:codecarbon:Could not measure RAM Power ([Errno 12] Cannot allocate memory)
```

You can see how the tracker has been initialized here:

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/350fb903935f900f400f140d157165d5fa4d7645/megatron/global_vars.py#L170-L175

@benoit-cty

**Comment by stas00** [comment]
Read the SO links, it suggests various strategies that we have no access to, since we have on sudo. there is no swap on the compute nodes either.

Someone suggested `gc.collect()` before forking the processes. (which may help since as you know gc doesn't run all the time)

And there is a ton of memory to go around unless, there is some strange burst at the beginning which gets released right away.

As mentioned in the comment above the key is whether this loses a tiny amount of recording and then continues functioning normally afterwards, or whether this is a critical error. If it's relatively benign, then we can just leave it alone.

I'm going to use log level "error" since we don't want any irrelevant logs to interfere with the training logs. So before I turn warnings off I wanted to check that it's safe to do so.

**Comment by vict0rsch** [comment]
I think it's tiny but let's look at orders of magnitudes:

```
30 (GB) * 3/8 (W/GB) = 11.25W 
```

comparatively a V100 is `300W` so I'd say if this is occasional it's ok, if it's systematic you'd underestimate by `11.25 * 20 = 225Wh = 0.225 kWh`

**Comment by vict0rsch** [comment]
> what does it mean from the point of measuring? Are we not measuring something when this happens? i.e. the results will be skewed.

It is true in theory indeed, just like using `codecarbon` has a CPU footprint in itself but it's measured as part of your computational cost so it's supposed to be taken into account.

Our working hypothesis is that `codecarbon` has a small CPU/RAM impact _compared to the job it tracks_, which is why I am very surprised too to see that such small operations would trigger a memory error, especially on a system with more than enough memory. 

Unfortunately I don't have access to an HPC infra so I can't really try and reproduce, you're the first to notice such a behaviour :(

**Comment by vict0rsch** [comment]
Looking at this https://stackoverflow.com/questions/9850995/tracking-maximum-memory-usage-by-a-python-function and installing `memory_profiler` I see reasonable numbers on multiple runs

```python
from memory_profiler import memory_usage
from time import sleep
from codecarbon import EmissionsTracker

def f():
    cc = EmissionsTracker(measure_power_secs=3)
    cc.start()
    sleep(21)
    cc.stop()

mem_usage = memory_usage(f)
print('Maximum memory usage: %s' % max(mem_usage))
print('Minimum memory usage: %s' % min(mem_usage))
```

```
Maximum memory usage: 91.74609375
Minimum memory usage: 86.48046875
```

```
Maximum memory usage: 91.7109375
Minimum memory usage: 86.5625
```

```
Maximum memory usage: 91.69140625
Minimum memory usage: 86.5234375
```

**Comment by benoit-cty** [comment]
Closing old issue.
