### ISSUE TITLE
emissions is 0.0 vs null

### ISSUE THREAD

**Issue by dsblank** [mlco2/codecarbon#25]
When I run an experiment with codecarbon without a GPU, I get the resulting `emissions.csv` data:

```csv
experiment_id,timestamp,project_name,duration,emissions,energy_consumed,country_name,country_iso_code,region,on_cloud,cloud_provider,cloud_region
51d77d04-33a7-4ca6-b55a-b157b0262e7b,2020-09-18T13:00:51,carbon-footprint,51.45621919631958,0.0,0.0,United States,USA,california,N,,
```

I thought the emissions value might be one that I could tell that it didn't record (for example `null`) and then I could fake a result based on the time the experiment ran and typical CPU usage in the USA or world. But I can't tell the difference between having a GPU with zero emissions, vs not having a GPU at all.

Any ideas what we can do here?

**Comment by vict0rsch** [comment]
good point. do you think having a `null` value would be enough? provided it's described as being "absence of recording" in the docs

**Comment by dsblank** [comment]
From what I have seen so far, I think `null` would be fine to represent "no time used by GPU" and `0` or `0.0` to represent zero time spent in the GPU. According to the [JSON docs](https://www.json.org/json-en.html) `null` is a valid value.

**Comment by vict0rsch** [comment]
Ok, will do then

**Comment by vict0rsch** [comment]
@kngoyal we need to update the dash viz accordingly to filter out those null values (@dsblank checking that, it seems like the standard `null` in csv is and empty string `""`)

**Comment by QS5526** [comment]
Hello everyone,
So if with have 0.0 as result, it means to represent zero time spent in the GPU and null "no time used by GPU".
And if all calcul has been done in CPU, what is the result for a complex algorithm?

**Comment by benoit-cty** [comment]
Fixed by https://github.com/mlco2/codecarbon/issues/29
