### ISSUE TITLE
CC crashes after `stop` was called.

### ISSUE THREAD

**Issue by stas00** [mlco2/codecarbon#251]
* CodeCarbon version: master
* Python version: 3.8
* Operating System: Ubuntu

### Description

We finally deployed codecarbon at the BigScience training and it worked fine for a while and just now on shutdown it crashed with the following tb on each process (256 in total of these) (I didn't count but it looked many all of them)

```
ERROR:apscheduler.scheduler:Error submitting job "BaseEmissionsTracker._measure_power (trigger: interval[0:01:00], next run at: 2021-09-25 01:43:20 CEST)" to executor "default"
Traceback (most recent call last):
  File "/gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 979, in _process_jobs
    executor.submit_job(job, run_times)
  File "/gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "/gpfswork/rech/six/commun/conda/tr1-13B/lib/python3.8/concurrent/futures/thread.py", line 179, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown
```

### What I Did

This happened after `.stop()` was already called and the program was shutting down.

To remind, here is how we set up the tracker:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/c839a8aa30731f71b3738d56009be9668508e366/megatron/global_vars.py#L155-L186

and this crash happened after stop was called here:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/c839a8aa30731f71b3738d56009be9668508e366/megatron/training.py#L170

My gut feeling is that stop didn't stop one of the CC instances and it tried to do its work, we are using 3 instances:
https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/c839a8aa30731f71b3738d56009be9668508e366/megatron/global_vars.py#L174

Thanks!

**Comment by stas00** [comment]
BTW, with all the extras we added as recommended in the previous PRs/Issues where we discussed this I see it's still reporting:
```
WARNING:apscheduler.executors.default:Run time of job "BaseEmissionsTracker._measure_power (trigger: interval[0:01:00], next run at: 2021-09-24 04:02:16 CEST)" was missed by 0:00:03.600668
```
quite a few of these, you can grep the log file here:
https://huggingface.co/bigscience/tr8-104B-logs/raw/main/logs/main_log.txt

so am I correct to understand that it's under-reporting?

**Comment by vict0rsch** [comment]
Hey @stas00  sorry it took us time to notice your issue. I'll have a go at it tomorrow, thanks for your reporting!
