### ISSUE TITLE
Create API endpoints for Dashboard integration

### ISSUE THREAD

**Issue by Minervabooks** [mlco2/codecarbon#255]
In order to create the new dashboard for code carbon, the dataviz team need the following entry points:

Commons entries to add to all route:
- `start_date` and `end_date` for _optional_ date range
- `page` (default=1) and `size` (default=1000) for pagination (See `/emissions/run/{run_id}` )
 

- [ ] 1. To enable to get data on Experiments, Runs and Emissions based on a date range
1.1 /​emissions​/run​/{run_id}/startDate=date1&endDate=date2
1.2 /runs/experiment/{experiment_id}/startDate=date1&endDate=date2
1.3 /experiments/project/{project_id}/startDate=date1&endDate=date2

- [ ] 2.  To be able to get the projects for a user ( get the projects of his organization)
`/user/{user_id}/projects`

- [ ] 3a. To be able to fetch the following aggregated data on organization level:
`/organizations/sums`
3.1 energy_consumed 
3.2 emissions_sum
3.3 duration 
3.4 organization name
3.5 organization description

- [ ] 3b. To be able to fetch the following aggregated data on team level:
`/teams/{organization_id}/sums`
3.1 energy_consumed 
3.2 emissions_sum
3.3 duration 
3.4 organization name
3.5 organization description

- [ ] 4a. To be able to fetch the following aggregated data on project level:
`/project/{project_id}/sums`
4.1 energy consumed
4.2 emissions_sum
4.3 duration
4.4 project name
4.5 project description

- [ ] 4b. To be able to fetch the following aggregated data on project level:
`/projects/{team_id}/sums`
4.1 energy consumed
4.2 emissions_sum
4.3 duration
4.4 project name
4.5 project description

- [] 5a. To be able to fetch the following aggregated data on experiment level:
`/experiment/{experiment_id}/sums/`
5.1 energy consumed 
5.2 emissions_sum 
5.3 duration
5.4 Experiment name
5.6 Experiment_id
5.7 Experiment description
5.8 Experiment start date

- [x] 5b. To be able to fetch the following aggregated data on experiment level:
`/experiments/{project_id}/sums/`
5.1 energy consumed 
5.2 emissions_sum 
5.3 duration
5.4 Experiment name
5.6 Experiment_id
5.7 Experiment description
5.8 Experiment start date

- [ ] 6. To be able to fetch the following aggregated data on run level for x last runs:
`/runs/{experiment_id}/get_latest?number=20`
6.1 energy consumed 
6.2 emissions_sum 
6.3 duration
6.4 Run_id
6.7 Run start date

**Comment by benoit-cty** [comment]
Great ! I think we need optional date range on all `global_sums` entries.

**Comment by MarionCoutarel** [comment]
indeed. We planed, when we discussed it, that the  call would be depending on  a startingDate and an endingDate parameters

**Comment by SaboniAmine** [comment]
Closing this as first endpoints have been implemented. We'll do another pass on what's needed for dataviz, with more up-to-date issues
