### ISSUE TITLE
Enabling report of cpu_power, gpu_power, ram_power, cpu_energy, gpu_energy, and ram_energy

### ISSUE THREAD

**Issue by TrevorVillwock** [mlco2/codecarbon#284]
* CodeCarbon version: 1.2.0
* Python version: 3.9.7
* Operating System: Ubuntu 18.04.5
* CPU: Intel(R) Xeon(R) CPU E5-2609 v4 @ 1.70GHz
* GPU: NVIDIA GeForce GTX 1080

### Description

When I run the mnist.py example, the csv file produced is missing several columns from the example emissions.csv file, including emissions_rate, cpu_power, gpu_power, ram_power, cpu_energy, gpu_energy, and ram_energy. What can I change to enable output of this data? Does this mean that my hardware doesn't support reporting it? Thank you for any help you can provide. Apologies if I missed anything about this in the documentation.

### What I Did

Ran `python mnist.py` after changing the number of epochs in it to 50, which produced this csv file:

![CodeCarbonRangerOutput](https://user-images.githubusercontent.com/56562687/154742642-bd69b416-ee5d-45d3-a35f-adecf7b53850.png)

**Comment by benoit-cty** [comment]
Hello,

Thanks for reporting, we have a v2.0.0 ready to be tested in few days that probably fix that. I will let you know.

**Comment by benoit-cty** [comment]
@hb9eik could you try with `pip install -U codecarbon==2.0.0a2` ?

But it will probably be same as "emissions_rate, cpu_power, gpu_power, ram_power, cpu_energy, gpu_energy, and ram_energy" has been added for the API, they don't exist in v1.2.0.
Did you install from pip or did you use `master` from github ?

**Comment by TrevorVillwock** [comment]
`pip install -U codecarbon==2.0.0a2` works, thanks! I had initially just done `pip install codecarbon` but after installing it from `master` with `pip install -e .` I was able to see those power and energy fields. I had to tweak some things to see the cpu data in the csv though and I wasn't sure if I was doing things right so it's nice to have the official version 2.0.0.

**Comment by benoit-cty** [comment]
Yes, we have a problem with Intel CPU under Linux, and we are working on it. I hope it will be solved before the end of the week.

**Comment by benoit-cty** [comment]
Hello,
The V2 package is out, could you give it a try ?

**Comment by benoit-cty** [comment]
Closed since there is no update on the issue.

**Comment by TrevorVillwock** [comment]
Hello again, sorry for my lack of response; school and life have kept me quite busy and I missed the alerts. It seems to be working now, thank you!

**Comment by benoit-cty** [comment]
Nice, thanks for coming back to us.
