### ISSUE TITLE
Power reported as W but are kW

### ISSUE THREAD

**Issue by hb9eik** [mlco2/codecarbon#286]
* CodeCarbon version: 1.2.0-py37_plus
* Python version: 3.9.7
* Operating System: Ubuntu focal

### Description
I was trying to get cpu power usages.
In this first time without load, only to test "noise floor" by operating system.
I have no GPU on board, I tested the CPUs power consumptions.
It seems that the power reported is a 3 order of magnitude lesser than correct.
It seems that it takes kW for W: an Haskell core cannot use 3mW, it seems than 3W is more realistic.
These are not only my feelings, I've checked with another program to be sure before submitting this report.

### What I Did
I run the EmissionTracker from python to see the basic values
Then run rapl-read.c from https://web.eece.maine.edu/~vweaver/projects/rapl/
to test if the data are similar and found a big discordance
digging into the code I've understood that module core.rapl.py determines the power values in kW
but externals.hardware.py manage this value as if is W (return Power.from_watts(power) on line 98)
```
>>> from codecarbon import EmissionsTracker
>>> tracker = EmissionsTracker()
>>> tracker.start()
>>> tracker.stop()
2.2974399653559338e-09
```

**Comment by benoit-cty** [comment]
Hello,

Thanks for reporting, we have a v2.0.0 ready to be tested in few days that probably fix that. I will let you know.

**Comment by benoit-cty** [comment]
@hb9eik could you try with `pip install -U codecarbon==2.0.0a2` ?

**Comment by hb9eik** [comment]
I tried but the problem seems to be the same, also it seems not to have files in data/private_infra
Now I'll try to find and insert these files to make more tests

**Comment by hb9eik** [comment]
the program fails telling:
[codecarbon WARNING @ 23:30:17] <class 'Exception'>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/codecarbon/core/util.py", line 18, in suppress
    yield
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/codecarbon/emissions_tracker.py", line 407, in stop
    emissions_data = self._prepare_emissions_data()
  File "/usr/local/lib/python3.8/dist-packages/codecarbon/emissions_tracker.py", line 427, in _prepare_emissions_data
    emissions = self._emissions.get_private_infra_emissions(
  File "/usr/local/lib/python3.8/dist-packages/codecarbon/core/emissions.py", line 108, in get_private_infra_emissions
    return self.get_country_emissions(energy, geo)
  File "/usr/local/lib/python3.8/dist-packages/codecarbon/core/emissions.py", line 157, in get_country_emissions
    energy_mix = self._data_source.get_global_energy_mix_data()
  File "/usr/local/lib/python3.8/dist-packages/codecarbon/input.py", line 74, in get_global_energy_mix_data
    with open(self.global_energy_mix_data_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/codecarbon/data/private_infra/global_energy_mix.json'
[codecarbon WARNING @ 23:30:17] stopping.

Sorry, but I'm not able to find any file into private_infra folder,

**Comment by hb9eik** [comment]
I was able to recover the file global_energy_mix.json 
from https://raw.githubusercontent.com/mlco2/codecarbon/master/codecarbon/data/private_infra/global_energy_mix.json 
and I continued the tests.
But I saw that the tool reported cpu_power as 0.0 that seems irrealistic, and report all power as used by the ram.
the file emissions.csv looks like this:
timestamp,project_name,run_id,duration,emissions,emissions_rate,cpu_power,gpu_power,ram_power,cpu_energy,gpu_energy,ram_energy,energy_consumed,country_name,country_iso_code,region,cloud_provider,cloud_region,os,python_version,cpu_count,cpu_model,gpu_count,gpu_model,longitude,latitude,ram_total_size,tracking_mode,on_cloud
2022-03-10T23:40:39,codecarbon,d46c1578-dbe5-4796-8658-acb180ba48fa,4.7366015911102295,4.286693241058345e-07,9.050145254149552e-05,0.0,0.0,3.084427776,0,0,2.0220251137067662e-06,2.0220251137067662e-06,Italy,ITA,lombardy,,,Linux-5.4.0-104-generic-x86_64-with-glibc2.29,3.8.10,4,Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz,,,9.1501,45.6105,8.225140736,machine,N
2022-03-10T23:45:10,codecarbon,48648823-8e80-4510-a076-f3ce107791d3,44.90998816490173,6.800382111264253e-06,0.00015142248727152683,0.0,0.0,3.084427776,0,0,3.207727410973704e-05,3.207727410973704e-05,Italy,ITA,lombardy,,,Linux-5.4.0-104-generic-x86_64-with-glibc2.29,3.8.10,4,Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz,,,9.1501,45.6105,8.225140736,machine,N

the debug during the run is this:
root@aurora:/home/giovanni# python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from codecarbon import EmissionsTracker
>>> tracker = EmissionsTracker()
[codecarbon INFO @ 23:44:15] [setup] RAM Tracking...
[codecarbon INFO @ 23:44:15] [setup] GPU Tracking...
[codecarbon INFO @ 23:44:15] No GPU found.
[codecarbon INFO @ 23:44:15] [setup] CPU Tracking...
[codecarbon INFO @ 23:44:15] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 23:44:16] >>> Tracker's metadata:
[codecarbon INFO @ 23:44:16]   Platform system: Linux-5.4.0-104-generic-x86_64-with-glibc2.29
[codecarbon INFO @ 23:44:16]   Python version: 3.8.10
[codecarbon INFO @ 23:44:16]   Available RAM : 8.225140736 GB
[codecarbon INFO @ 23:44:16]   CPU count: 4
[codecarbon INFO @ 23:44:16]   CPU model: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
[codecarbon INFO @ 23:44:16]   GPU count: None
[codecarbon INFO @ 23:44:16]   GPU model: None
>>> tracker.start()
>>> [codecarbon INFO @ 23:44:40] Energy consumed for all RAM : 0.000000 kWh
tractracker.stop()
[codecarbon INFO @ 23:44:47] Energy consumed for all RAM : 0.000013 kWh
[codecarbon INFO @ 23:44:55] Energy consumed for all CPUs : 0.000032 kWh
[codecarbon INFO @ 23:44:55] 0.000032 kWh of electricity used since the begining.
[codecarbon INFO @ 23:45:10] Energy consumed for all CPUs : 0.000032 kWh
[codecarbon INFO @ 23:45:10] 0.000032 kWh of electricity used since the begining.
/usr/local/lib/python3.8/dist-packages/codecarbon/output.py:117: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(dict(data.values), ignore_index=True)
6.800382111264253e-06
>>> 

Should this be a problem in csv file generation?
in the debug it states that the total energy is 0.000032 kWh and 0.000013 kWh is from RAM
but it reported power from ram (3.084427776W that seems reasonable) but not from CPU (0.0W)
also, if you compare power from RAM (that is the same in the two runs), duration of the two runs, and energy from ram, the computations are not consistent and any tentative to derive energy from ram power consumption and time seems to fail ...
3.084427776 * 4.7366015911102295 /3600 /1000 =.0000040 that differs from 2.0220251137067662e-06 (=.0000020220251137067662)
3.084427776W * 44.90998816490173s /3600 /1000 = .0000384 kWh that differs from 3.207727410973704e-05 (=.00003207727410973704)

**Comment by benoit-cty** [comment]
Thanks, I've found the problem for `global_energy_mix.json` (a missing comma in setup.py) : https://github.com/mlco2/codecarbon/pull/290

@vict0rsch do you have an idea on other problems ?

**Comment by benoit-cty** [comment]
We indeed have a bug in CPU power monitoring, a patch in on his way.

**Comment by benoit-cty** [comment]
What I get with the branch release-patch-3:
Content of /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj when I start the script for 10 minutes: 51177839565
Content of /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj when I stop the script after 10 minutes: 52591878792
So a consumption of 1 414 039 227 microjoules.

What Code Carbon tell me:
```
[codecarbon DEBUG @ 23:13:23] GO!
[codecarbon INFO @ 23:13:23] [setup] RAM Tracking...
[codecarbon INFO @ 23:13:23] [setup] GPU Tracking...
[codecarbon INFO @ 23:13:23] No GPU found.
[codecarbon INFO @ 23:13:23] [setup] CPU Tracking...
[codecarbon DEBUG @ 23:13:23] Not using PowerGadget, an exception occurred while instantiating IntelPowerGadget : Platform not supported by Intel Power Gadget
[codecarbon DEBUG @ 23:13:23] We will read Intel RAPL files at /sys/class/powercap/intel-rapl/intel-rapl:1/energy_uj
[codecarbon DEBUG @ 23:13:23] We will read Intel RAPL files at /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
[codecarbon INFO @ 23:13:23] Tracking Intel CPU via RAPL interface
[codecarbon DEBUG @ 23:13:24] We will read Intel RAPL files at /sys/class/powercap/intel-rapl/intel-rapl:1/energy_uj
[codecarbon DEBUG @ 23:13:24] We will read Intel RAPL files at /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
[codecarbon INFO @ 23:13:24] >>> Tracker's metadata:
[codecarbon INFO @ 23:13:24]   Platform system: Linux-5.13.0-30-generic-x86_64-with-glibc2.29
[codecarbon INFO @ 23:13:24]   Python version: 3.8.10
[codecarbon INFO @ 23:13:24]   Available RAM : 15.512 GB
[codecarbon INFO @ 23:13:24]   CPU count: 4
[codecarbon INFO @ 23:13:24]   CPU model: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
[codecarbon INFO @ 23:13:24]   GPU count: None
[codecarbon INFO @ 23:13:24]   GPU model: None
[codecarbon DEBUG @ 23:13:25] Not running on AWS, couldn't retrieve metadata: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /latest/dynamic/instance-identity/document (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc4690e42b0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))"))
[codecarbon DEBUG @ 23:13:26] Not running on Azure, couldn't retrieve metadata: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /metadata/instance?api-version=2019-08-15 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc4691063a0>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))"))
[codecarbon DEBUG @ 23:13:27] Not running on GCP, couldn't retrieve metadata: ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='169.254.169.254', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/?recursive=true&alt=json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc469106c40>, 'Connection to 169.254.169.254 timed out. (connect timeout=1)'))"))
600 seconds before ending script...
[codecarbon INFO @ 23:13:57] Energy consumed for RAM : 0.000048 kWh. RAM Power : 5.8171234130859375 W
[codecarbon DEBUG @ 23:13:57] RAM : 5.82 W during 30.01 s [measurement time: 0.0010]
[codecarbon DEBUG @ 23:13:57] RAPLFile(name='psys', path='/sys/class/powercap/intel-rapl/intel-rapl:1/energy_uj', energy_reading=Energy(kWh=0), energy_delta=Energy(kWh=0.00022005125520753455), power=Power(kW=0.026400979916016965))
[codecarbon DEBUG @ 23:13:57] RAPLFile(name='Processor Energy Delta_0(kWh)', path='/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj', energy_reading=Energy(kWh=0), energy_delta=Energy(kWh=1.8607348219200348e-05), power=Power(kW=0.00223244455552927))
[codecarbon DEBUG @ 23:13:57] get_cpu_details {'psys': 0.00022005125520753455, 'Processor Energy Delta_0(kWh)': 1.8607348219200348e-05, 'Processor Power Delta_0(kWh)': 2.23244455552927}
[codecarbon DEBUG @ 23:13:57] _get_energy_from_cpus - DONT MATCH psys : 0.00022005125520753455
[codecarbon DEBUG @ 23:13:57] _get_energy_from_cpus - MATCH Processor Energy Delta_0(kWh) : 1.8607348219200348e-05
[codecarbon DEBUG @ 23:13:57] _get_energy_from_cpus - DONT MATCH Processor Power Delta_0(kWh) : 2.23244455552927
[codecarbon DEBUG @ 23:13:57] get_static_cpu_details {'psys': 0.00022005125520753455, 'Processor Energy Delta_0(kWh)': 1.8607348219200348e-05, 'Processor Power Delta_0(kWh)': 2.23244455552927}
[codecarbon DEBUG @ 23:13:57] _get_power_from_cpus - DONT MATCH psys : 0.00022005125520753455
[codecarbon DEBUG @ 23:13:57] _get_power_from_cpus - DONT MATCH Processor Energy Delta_0(kWh) : 1.8607348219200348e-05
[codecarbon DEBUG @ 23:13:57] _get_power_from_cpus - MATCH Processor Power Delta_0(kWh) : 2.23244455552927
[codecarbon INFO @ 23:13:57] Energy consumed for all CPUs : 0.000019 kWh. All CPUs Power : 2.23244455552927 W
[codecarbon DEBUG @ 23:13:57] get_static_cpu_details {'psys': 0.00022005125520753455, 'Processor Energy Delta_0(kWh)': 1.8607348219200348e-05, 'Processor Power Delta_0(kWh)': 2.23244455552927}
[codecarbon DEBUG @ 23:13:57] _get_power_from_cpus - DONT MATCH psys : 0.00022005125520753455
[codecarbon DEBUG @ 23:13:57] _get_power_from_cpus - DONT MATCH Processor Energy Delta_0(kWh) : 1.8607348219200348e-05
[codecarbon DEBUG @ 23:13:57] _get_power_from_cpus - MATCH Processor Power Delta_0(kWh) : 2.23244455552927
[codecarbon DEBUG @ 23:13:57] CPU : 2.23 W during 30.01 s [measurement time: 0.0030]
[codecarbon INFO @ 23:13:57] 0.000067 kWh of electricity used since the begining.
```
Then, at the end:
```
[codecarbon INFO @ 23:23:27] Energy consumed for RAM : 0.000969 kWh. RAM Power : 5.8171234130859375 W
[codecarbon DEBUG @ 23:23:27] RAM : 5.82 W during 30.00 s [measurement time: 0.0008]
[codecarbon DEBUG @ 23:23:27] RAPLFile(name='psys', path='/sys/class/powercap/intel-rapl/intel-rapl:1/energy_uj', energy_reading=Energy(kWh=0), energy_delta=Energy(kWh=0.000132050599529282), power=Power(kW=0.015847712646020855))
[codecarbon DEBUG @ 23:23:27] RAPLFile(name='Processor Energy Delta_0(kWh)', path='/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj', energy_reading=Energy(kWh=0), energy_delta=Energy(kWh=8.597888822750588e-06), power=Power(kW=0.0010318534857933085))
[codecarbon DEBUG @ 23:23:27] get_cpu_details {'psys': 0.000132050599529282, 'Processor Energy Delta_0(kWh)': 8.597888822750588e-06, 'Processor Power Delta_0(kWh)': 1.0318534857933084}
[codecarbon DEBUG @ 23:23:27] _get_energy_from_cpus - DONT MATCH psys : 0.000132050599529282
[codecarbon DEBUG @ 23:23:27] _get_energy_from_cpus - MATCH Processor Energy Delta_0(kWh) : 8.597888822750588e-06
[codecarbon DEBUG @ 23:23:27] _get_energy_from_cpus - DONT MATCH Processor Power Delta_0(kWh) : 1.0318534857933084
[codecarbon DEBUG @ 23:23:27] get_static_cpu_details {'psys': 0.000132050599529282, 'Processor Energy Delta_0(kWh)': 8.597888822750588e-06, 'Processor Power Delta_0(kWh)': 1.0318534857933084}
[codecarbon DEBUG @ 23:23:27] _get_power_from_cpus - DONT MATCH psys : 0.000132050599529282
[codecarbon DEBUG @ 23:23:27] _get_power_from_cpus - DONT MATCH Processor Energy Delta_0(kWh) : 8.597888822750588e-06
[codecarbon DEBUG @ 23:23:27] _get_power_from_cpus - MATCH Processor Power Delta_0(kWh) : 1.0318534857933084
[codecarbon INFO @ 23:23:27] Energy consumed for all CPUs : 0.000384 kWh. All CPUs Power : 1.0318534857933084 W
[codecarbon DEBUG @ 23:23:27] get_static_cpu_details {'psys': 0.000132050599529282, 'Processor Energy Delta_0(kWh)': 8.597888822750588e-06, 'Processor Power Delta_0(kWh)': 1.0318534857933084}
[codecarbon DEBUG @ 23:23:27] _get_power_from_cpus - DONT MATCH psys : 0.000132050599529282
[codecarbon DEBUG @ 23:23:27] _get_power_from_cpus - DONT MATCH Processor Energy Delta_0(kWh) : 8.597888822750588e-06
[codecarbon DEBUG @ 23:23:27] _get_power_from_cpus - MATCH Processor Power Delta_0(kWh) : 1.0318534857933084
[codecarbon DEBUG @ 23:23:27] CPU : 1.03 W during 30.00 s [measurement time: 0.0024]
[codecarbon INFO @ 23:23:27] 0.001354 kWh of electricity used since the begining.
[codecarbon INFO @ 23:23:28] 
Graceful stopping: collecting and writing information.
Please Allow for a few seconds...
[codecarbon INFO @ 23:23:28] Energy consumed for RAM : 0.000970 kWh. RAM Power : 5.8171234130859375 W
[codecarbon DEBUG @ 23:23:28] RAM : 5.82 W during 0.51 s [measurement time: 0.0003]
[codecarbon DEBUG @ 23:23:28] RAPLFile(name='psys', path='/sys/class/powercap/intel-rapl/intel-rapl:1/energy_uj', energy_reading=Energy(kWh=0), energy_delta=Energy(kWh=3.4674522183947287e-06), power=Power(kW=0.024268133669251124))
[codecarbon DEBUG @ 23:23:28] RAPLFile(name='Processor Energy Delta_0(kWh)', path='/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj', energy_reading=Energy(kWh=0), energy_delta=Energy(kWh=8.613570779726631e-07), power=Power(kW=0.006028497983131121))
[codecarbon DEBUG @ 23:23:28] get_cpu_details {'psys': 3.4674522183947287e-06, 'Processor Energy Delta_0(kWh)': 8.613570779726631e-07, 'Processor Power Delta_0(kWh)': 6.02849798313112}
[codecarbon DEBUG @ 23:23:28] _get_energy_from_cpus - DONT MATCH psys : 3.4674522183947287e-06
[codecarbon DEBUG @ 23:23:28] _get_energy_from_cpus - MATCH Processor Energy Delta_0(kWh) : 8.613570779726631e-07
[codecarbon DEBUG @ 23:23:28] _get_energy_from_cpus - DONT MATCH Processor Power Delta_0(kWh) : 6.02849798313112
[codecarbon DEBUG @ 23:23:28] get_static_cpu_details {'psys': 3.4674522183947287e-06, 'Processor Energy Delta_0(kWh)': 8.613570779726631e-07, 'Processor Power Delta_0(kWh)': 6.02849798313112}
[codecarbon DEBUG @ 23:23:28] _get_power_from_cpus - DONT MATCH psys : 3.4674522183947287e-06
[codecarbon DEBUG @ 23:23:28] _get_power_from_cpus - DONT MATCH Processor Energy Delta_0(kWh) : 8.613570779726631e-07
[codecarbon DEBUG @ 23:23:28] _get_power_from_cpus - MATCH Processor Power Delta_0(kWh) : 6.02849798313112
[codecarbon INFO @ 23:23:28] Energy consumed for all CPUs : 0.000385 kWh. All CPUs Power : 6.02849798313112 W
[codecarbon DEBUG @ 23:23:28] get_static_cpu_details {'psys': 3.4674522183947287e-06, 'Processor Energy Delta_0(kWh)': 8.613570779726631e-07, 'Processor Power Delta_0(kWh)': 6.02849798313112}
[codecarbon DEBUG @ 23:23:28] _get_power_from_cpus - DONT MATCH psys : 3.4674522183947287e-06
[codecarbon DEBUG @ 23:23:28] _get_power_from_cpus - DONT MATCH Processor Energy Delta_0(kWh) : 8.613570779726631e-07
[codecarbon DEBUG @ 23:23:28] _get_power_from_cpus - MATCH Processor Power Delta_0(kWh) : 6.02849798313112
[codecarbon DEBUG @ 23:23:28] CPU : 6.03 W during 0.51 s [measurement time: 0.0006]
[codecarbon INFO @ 23:23:28] 0.001355 kWh of electricity used since the begining.
[codecarbon DEBUG @ 23:23:28] We apply an energy mix of 55 g.CO2eq/kWh for France
[codecarbon DEBUG @ 23:23:28] EmissionsData(timestamp='2022-03-15T23:23:28', project_name='codecarbon', run_id='8038d4a7-c36d-476e-bf39-5bd61842b0a3', duration=600.5415604114532, emissions=7.454555674695947e-05, emissions_rate=0.00012413055425487216, cpu_power=6.02849798313112, gpu_power=0.0, ram_power=5.8171234130859375, cpu_energy=0.0003851681011897909, gpu_energy=0, ram_energy=0.0009702056578458361, energy_consumed=0.0013553737590356269, country_name='France', country_iso_code='FRA', region='île-de-france', cloud_provider='', cloud_region='', os='Linux-5.13.0-30-generic-x86_64-with-glibc2.29', python_version='3.8.10', cpu_count=4, cpu_model='Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz', gpu_count=None, gpu_model=None, longitude=2.3859, latitude=48.6831, ram_total_size=15.5123291015625, tracking_mode='machine', on_cloud='N')
[codecarbon INFO @ 23:23:28] Done!
```

**Comment by benoit-cty** [comment]
Sorry for the delay, could you test with `pip install codecarbon==2.0.0a3` ?

**Comment by hb9eik** [comment]
You're welcome,
don't worry, no delay, I'm very pleased to see that the problem was addressed.
At a first look the numbers seem "good", but I've made some checks on the spreadsheet, computing joules in two distinct modes (cpu power* duration - see cells G5 and G6), and (cpu energy(kwh)*3600000 - see cells J5 and J6) and the values differ. Could this be a problem of rounding?
The same is for ram energy (cells I5 I6 and L5 L6).
Tomorrow I'll do other tests reading directly the statistics from the CPU.
Many thanks for your work, much appreciated.
Have a nice weekend,

Giovanni
[emissions.csv](https://github.com/mlco2/codecarbon/files/8308078/emissions.csv)
[emissions-controls.odf](https://github.com/mlco2/codecarbon/files/8308080/emissions-controls.odf)

**Comment by hb9eik** [comment]
This issue can be considered closed and solved.
I have created a new bug (#292) because I've found that the problem with calculation seems related with an imprecision in duration report and not with the power probblem.
Many thanks for the solution and your effort.
