### ISSUE TITLE
Prevent duplicate entry on API

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#299]
* CodeCarbon version: 2.0.0

### Description

The API routes did not check if an entity with same name and same parent id already exist.

### What I Did

Call two time the same API entry with same payload.

### What I expect

An error message.

### What I get

The entry was created two times.

**Comment by benoit-cty** [comment]
See also #507 and #508

**Comment by SaboniAmine** [comment]
Closing this issue as it has been fixed.
