### ISSUE TITLE
Print version of package in log and API metadata

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#302]
* CodeCarbon version:2.1.0

### Description
* We need to add version in starting log to let user know which version they are using.
* We need the package version in run metadata, so if a package as a problem we may could fix the database.

### How to do it

Since 2.1.0 we have version available through `codecarbon.__version__` so it is easy to log it and send it to the API.

**Comment by pokacyb** [comment]
Hi @benoit-cty,

I'm trying this right now but running into a bit of issue.
Basically whatever I change in the code is not reflecting on output.

![Screenshot from 2022-06-30 21-43-37](https://user-images.githubusercontent.com/77896376/176763853-61df4f7a-eca4-4c9f-85f7-4b85fa8eb08b.png)

For example even after deleting files I still get the same terminal output.
I tried creating new codecarbon init files but same result.
Is there something I'm doing wrong?

**Comment by benoit-cty** [comment]
Hi,
Thanks for your help 👍 
I think you are running the code from Pypi package, so you don't see local modification.
Did you install the code in "editable" mode with `pip install -e .` ?
(see https://github.com/mlco2/codecarbon/blob/master/CONTRIBUTING.md _Install from sources in development mode_ )
