### ISSUE TITLE
Errors for CPU tracking

### ISSUE THREAD

**Issue by mahmoodn** [mlco2/codecarbon#304]
Hi
May I know what is the correct way to fix the following errors:

```
[codecarbon INFO @ 13:11:29] [setup] RAM Tracking...
[codecarbon INFO @ 13:11:29] [setup] GPU Tracking...
[codecarbon INFO @ 13:11:29] Tracking Nvidia GPU via pynvml
[codecarbon INFO @ 13:11:29] [setup] CPU Tracking...
[codecarbon ERROR @ 13:11:29] Unable to read Intel RAPL files for CPU power, we will use a constant for your CPU power. Please view https://github.com/mlco2/codecarbon/issues/244 for workarounds : [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj'
[codecarbon INFO @ 13:11:29] Tracking Intel CPU via RAPL interface
[codecarbon ERROR @ 13:11:30] Unable to read Intel RAPL files for CPU power, we will use a constant for your CPU power. Please view https://github.com/mlco2/codecarbon/issues/244 for workarounds : [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj'
[codecarbon INFO @ 13:11:30] >>> Tracker's metadata:
[codecarbon INFO @ 13:11:30]   Platform system: Linux-5.13.0-27-generic-x86_64-with-glibc2.29
[codecarbon INFO @ 13:11:30]   Python version: 3.8.10
[codecarbon INFO @ 13:11:30]   Available RAM : 31.273 GB
[codecarbon INFO @ 13:11:30]   CPU count: 16
[codecarbon INFO @ 13:11:30]   CPU model: AMD Ryzen 7 3700X 8-Core Processor
[codecarbon INFO @ 13:11:30]   GPU count: 1
[codecarbon INFO @ 13:11:30]   GPU model: 1 x NVIDIA GeForce RTX 3080
```
Should I run the code with sudo access? Then I have to reinstall all pip packages that are needed. I wonder why it can not read RAPL data since I am able to run perf command with energy metrics and it works fine.

**Comment by benoit-cty** [comment]
Hi,
Thanks for reporting this. Please don't run your Python code with sudo. You could see explanation on the problem in https://github.com/mlco2/codecarbon/issues/244

Could you tell us more on "perf command with energy metrics" because we are highly interested in method that do not need root access at any time ?

**Comment by mp15** [comment]
Also I just noticed: `CPU model: AMD Ryzen 7 3700X 8-Core Processor`. As far as I can tell the Intel RAPL driver doesn't support AMD processors as they use different MSRs (machine specific registers) to communicate their power consumption.

**Comment by benoit-cty** [comment]
Absolutely, RAPL did not work with AMD CPU.

I will close this issue as we did not get enough information.
