### ISSUE TITLE
AttributeError: Jumbotron was deprecated in dash-bootstrap-components version 1.0.0. 

### ISSUE THREAD

**Issue by benoit-cty** [mlco2/codecarbon#319]
* CodeCarbon version: 2.1.3
* Python version: 3.8.12
* Operating System: Ubuntu 20.04

### Description

View the CarbonBoard.

### What I Did

```
python -m venv .venv-dasboad-legacy
source .venv-dasboad-legacy/bin/activate
pip install -e .[viz]
carbonboard --filepath="examples/emissions.csv" --port=3333
```

**Comment by benoit-cty** [comment]
Workaround:
`pip install dash-bootstrap-components==0.13.1`

**Comment by heaversm** [comment]
The issue doesn't seem to be fixed without manually running the pip command above as far as I can tell.
