### ISSUE TITLE
ERROR: EnergyDriver_executeCommands [via readSample] returned 0xe00002bc

### ISSUE THREAD

**Issue by MinnieM0use** [mlco2/codecarbon#321]
* CodeCarbon version: 2.1.2 and 2.1.3
* Python version: 3.9.4 and 3.7.7
* Operating System: macOS Big Sur 11.6.5

### Description

I am trying to wrap the EmissionTracker around a project but I get an error.

### What I Did

```
import sys
import pathlib
import os
from codecarbon import EmissionsTracker
import timeit

path = str(pathlib.Path(__file__).parent.resolve()) + "/pathToFile"
sys.path.append(path)
os.chdir(path)

with EmissionsTracker() as tracker:
    start = timeit.default_timer()
    import main
    stop = timeit.default_timer()
    print('Runtime: ', stop - start)  

sys.path.remove(path)
sys.modules.pop('main')
```

```
ERROR: EnergyDriver_executeCommands [via readSample] returned 0xe00002bc
```

The error appears multiple times in the terminal output

I would be happy with a workaround...

**Comment by benoit-cty** [comment]
Hello,
Thanks for reporting, this is a Power Gadget error. Which CPU are you using ? Could you give us the full log ?
