### ISSUE TITLE
Unexpected output after running `scontrol show job $SLURM_JOBID` to count SLURM-available RAM. Using the machine's total RAM.

### ISSUE THREAD

**Issue by lboesen** [mlco2/codecarbon#335]
CodeCarbon version: 2.1.4
Python version: Python 3.10.4
Operating System: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.17

### Description

Ran 1 python scripts in slurm scripts,(5 array jobs).  This is always the case for the last job(5)

### What I Did

[codecarbon WARNING @ 08:13:30] Unexpected output after running `scontrol show job $SLURM_JOBID` to count SLURM-available cpus. Using the machine's cpu count.
[codecarbon INFO @ 08:13:30] [setup] RAM Tracking...
[codecarbon WARNING @ 08:13:30] Unexpected output after running `scontrol show job $SLURM_JOBID` to count SLURM-available RAM. Using the machine's total RAM.
[codecarbon INFO @ 08:13:30] [setup] GPU Tracking...
[codecarbon INFO @ 08:13:30] No GPU found.
[codecarbon INFO @ 08:13:30] [setup] CPU Tracking...
[codecarbon INFO @ 08:13:30] Tracking Intel CPU via RAPL interface
[codecarbon INFO @ 08:13:30] >>> Tracker's metadata:
[codecarbon INFO @ 08:13:30]   Platform system: Linux-3.10.0-1160.62.1.el7.x86_64-x86_64-with-glibc2.17
[codecarbon INFO @ 08:13:30]   Python version: 3.10.4
[codecarbon INFO @ 08:13:30]   Available RAM : 125.717 GB
[codecarbon INFO @ 08:13:30]   CPU count: 40
[codecarbon INFO @ 08:13:30]   CPU model: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
[codecarbon INFO @ 08:13:30]   GPU count: None
[codecarbon INFO @ 08:13:30]   GPU model: None
[codecarbon WARNING @ 08:13:48] Unexpected output after running `scontrol show job $SLURM_JOBID` to count SLURM-available RAM. Using the machine's total RAM.
[codecarbon INFO @ 08:13:48] Energy consumed for RAM : 0.000196 kWh. RAM Power : 47.14397478103638 W
[codecarbon WARNING @ 08:13:48] Unexpected output after running `scontrol show job $SLURM_JOBID` to count SLURM-available RAM. Using the machine's total RAM.
[codecarbon INFO @ 08:13:48] Energy consumed for all CPUs : 0.000200 kWh. All CPUs Power : 47.80755402258252 W

**Comment by benoit-cty** [comment]
Thanks,
The problem seems to be we find more than one `mem=` in the result of `scontrol show job $SLURM_JOBID`, here is the code:
```py
    def _parse_scontrol(self, scontrol_str):
        mem_matches = re.findall(r"mem=\d+[A-Z]", scontrol_str)
        if len(mem_matches) == 0:
            logger.warning(
                "Could not find mem= after running `scontrol show job $SLURM_JOBID` "
                + "to count SLURM-available RAM. Using the machine's total RAM."
            )
            return psutil.virtual_memory().total / B_TO_GB
        if len(mem_matches) > 1:
            logger.warning(
                "Unexpected output after running `scontrol show job $SLURM_JOBID` "
                + "to count SLURM-available RAM. Using the machine's total RAM."
            )
            return psutil.virtual_memory().total / B_TO_GB

        return mem_matches[0].replace("mem=", "")
```
Can you run `scontrol show job $SLURM_JOBID` and provide the result ?

**Comment by lboesen** [comment]
JobId=2181679 ArrayJobId=2181679 ArrayTaskId=5 JobName=3000_bm25_run
   UserId=***(133073204) GroupId=users(100) MCS_label=N/A
   Priority=79 Nice=0 Account=*** QOS=normal
   JobState=RUNNING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=01:57:33 TimeLimit=03:00:00 TimeMin=N/A
   SubmitTime=2022-10-04T12:01:19 EligibleTime=2022-10-04T12:01:20
   AccrueTime=Unknown
   StartTime=2022-10-04T12:01:20 EndTime=2022-10-04T15:01:20 Deadline=N/A
   SuspendTime=None SecsPreSuspend=0 LastSchedEval=2022-10-04T12:01:20
   Partition=image1 AllocNode:Sid=a00552:30154
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=a00551
   BatchHost=a00551
   NumNodes=1 NumCPUs=8 NumTasks=1 CPUs/Task=8 ReqB:S:C:T=0:0:*:*
   TRES=cpu=8,mem=24000M,node=1,billing=13
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=8 MinMemoryCPU=3000M MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/***/3000bm25_slurm.sh
   WorkDir=/home/***
   StdErr=/home/***/slurm-2181679_5.out
   StdIn=/dev/null
   StdOut=/home/***/slurm-2181679_5.out
   Power=
   MailUser=*** MailType=BEGIN,END,FAIL
   NtasksPerTRES:0

**Comment by lboesen** [comment]
I turned out to be a fault from my side, there was some faulty nodes with the cluster I was using.
Sorry for the inconvenience - closing the issue

**Comment by benoit-cty** [comment]
Thanks for the update on the issue :+1:
