### ISSUE TITLE
Comet showing no data output / stuck on processing?

### ISSUE THREAD

**Issue by heaversm** [mlco2/codecarbon#338]
* CodeCarbon version: 2.1.4
* Python version: Python 3.10.6
* Operating System: MacOS 12.6

### Description

Describe what you were trying to get done.

Run the `mnist-comet.py` example from the readme in Comet

Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

* Add Comet API key
* In the [`[mnist-comet.py](https://github.com/mlco2/codecarbon/blob/master/examples/mnist-comet.py)`](https://github.com/mlco2/codecarbon/blob/master/examples/mnist-comet.py) example file:
replace `experiment = Experiment()`
With
`experiment = Experiment(api_key="[MY_API_KEY]")`
* and then run the example:
`python3 examples/mnist-comet.py`
* Added the emissions tracker `Codecarbon Footprint` panel in Comet
* Saved the view.

Code is running but the panel shows no meaningful data. 

<img width="970" alt="Screen Shot 2022-10-07 at 3 39 39 PM" src="https://user-images.githubusercontent.com/520541/194671963-418a805e-203e-474f-bc16-5e359cccfed9.png">

**Comment by heaversm** [comment]
Stopping the experiment from the command line ends at "Processing 100%" and the panel is now blank:

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/520541/194672158-5bbe809e-32b1-4634-9951-bf066f612601.png">

**Comment by heaversm** [comment]
This is the console output when I start training:

```
022-10-07 15:53:18.842331: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
[codecarbon INFO @ 15:53:24] [setup] RAM Tracking...
[codecarbon INFO @ 15:53:24] [setup] GPU Tracking...
[codecarbon INFO @ 15:53:24] No GPU found.
[codecarbon INFO @ 15:53:24] [setup] CPU Tracking...
[codecarbon INFO @ 15:53:24] Tracking Intel CPU via Power Gadget
[codecarbon INFO @ 15:53:25] >>> Tracker's metadata:
[codecarbon INFO @ 15:53:25]   Platform system: macOS-12.6-x86_64-i386-64bit
[codecarbon INFO @ 15:53:25]   Python version: 3.10.6
[codecarbon INFO @ 15:53:25]   Available RAM : 32.000 GB
[codecarbon INFO @ 15:53:25]   CPU count: 8
[codecarbon INFO @ 15:53:25]   CPU model: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
[codecarbon INFO @ 15:53:25]   GPU count: None
[codecarbon INFO @ 15:53:25]   GPU model: None
COMET INFO: Couldn't find a Git repository in '/Users/mheavers/Documents/Prototypes/Environment/code carbon' nor in any parent directory. You can override where Comet is looking for a Git Patch by setting the configuration `COMET_GIT_DIRECTORY`
COMET INFO: Experiment is live on comet.com https://www.comet.com/heaversm/general/be01805cf04a47fd98aa44a2e2b548db

2022-10-07 15:53:29.628779: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
COMET INFO: Ignoring automatic log_parameter('verbose') because 'keras:verbose' is in COMET_LOGGING_PARAMETERS_IGNORE
```

**Comment by vict0rsch** [comment]
@Lothiraldan

**Comment by benoit-cty** [comment]
@Lothiraldan do you have an idea on this issue with CodeCarbon in Comet ?

**Comment by benoit-cty** [comment]
Closing as we have no answer from Comet.
