### ISSUE TITLE
Impact Values not Updated for Google cloud 

### ISSUE THREAD

**Issue by hassenebyy** [mlco2/codecarbon#339]
Hello,

Please note that impact values are not updated on  codecarbon/data/cloud/impact.csv 

Find updated values in : https://cloud.google.com/sustainability/region-carbon?hl=fr

thank you.

**Comment by potter0815** [comment]
Hi, 

the values for AWS are also not up to date updated values are here below the Map: 

https://sustainability.aboutamazon.com/environment/the-cloud?energyType=true#renewable-energy-map

thanks

**Comment by esspee-lbg** [comment]
Hi all, if no one has picked up this. I wouldn't mind having ago

**Comment by MarionCoutarel** [comment]
Hi I created a branch and I update the google values (here https://github.com/mlco2/codecarbon/tree/UpdateData/codecarbon/data/cloud ) . If you have more recent values for aws and azure feel free to update the datas too 😄

**Comment by benoit-cty** [comment]
We just opened the PR https://github.com/mlco2/codecarbon/pull/350

GCP data has been updated from https://github.com/GoogleCloudPlatform/region-carbon-info/tree/main/data/yearly

If you could not find Azure or AWS data, I think we could switch to the country data in https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/private_infra/global_energy_mix.json
