### ISSUE TITLE
The codecarbon does not run

### ISSUE THREAD

**Issue by ChaeUn388** [mlco2/codecarbon#343]
* CodeCarbon version:All
* Python version:All
* Operating System:Windows 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
The codecarbon is incompatible with the Unity program.
Please tell me how to solve this

**Comment by benoit-cty** [comment]
Hello, could you tell us more about what you are trying to do ?
Unity use C langage, CodeCarbon is a Python library.
