### ISSUE TITLE
CO2eq in code carbon an expression in metric tons or kilometers?

### ISSUE THREAD

**Issue by karikraus** [mlco2/codecarbon#344]
Hi, thank you for this wonderful Python library! I'm trying to understand if the CO2eq output is expressed in metric tons or kilograms?

According to Cooler Future (https://www.coolerfuture.com/blog/co2e), "Carbon dioxide equivalents are commonly expressed as million metric tonnes of carbon dioxide equivalents (abbreviated as MMTCDE), but often you can see them in kilos too"

For example, using CodeCarbon, one output I got for fine-tuning GPT2 on a Victorian corpus was 0.02238809728762495

So which is it for Codecarbon: metric tonnes or kilos or something else?

Thank you!

**Comment by karikraus** [comment]
Reviewing the documentation again, I see that the output is expressed in kilograms. Thank you again for such a great resource.

**Comment by benoit-cty** [comment]
Thanks, @MarionCoutarel spend time updating units in documentation last week, she will be glad to hear that it helped you.
