### ISSUE TITLE
References needed for basis of calculating CO2 emissions

### ISSUE THREAD

**Issue by mkbane** [mlco2/codecarbon#351]
* CodeCarbon version:
* Python version:
* Operating System:

### Description

From reading the web page, I cannot determine how you measure (or is it estimate) the Carbon (or CO2?) emissions.

### What I Require
Description & References needed for basis of calculating CO2 emissions

**Comment by MarionCoutarel** [comment]
Hi,
You can find our data sources in the code here : https://github.com/mlco2/codecarbon/tree/master/codecarbon/data .
We mostly use 2 sources for private infra : 
- https://www.globalpetrolprices.com/energy_mix.php that use calculations based on data from the U.S. Energy Information Administration
-  https://ourworldindata.org/grapher/carbon-intensity-electricity 

For cloud infra the sources are list within the csv file here : https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/cloud/impact.csv

Thanks to your issue I'll  make it appears in the documentation.

Regards
