### ISSUE TITLE
EmissionTracker not updating .csv file, but create new

### ISSUE THREAD

**Issue by NicolaCST** [mlco2/codecarbon#364]
* CodeCarbon version: 2.1.4
* Python version: 3.8.16
* Operating System: Linux (Colab)

### Description
Hi all,
I was trying to update my .csv emission file with some results. However it keeps creating new "*.bak" file, even tho i've setted:

tracker = codecarbon.EmissionsTracker(output_dir = "/content/emissions/", 
                                                                output_file = "test.csv",
                                                                tracking_mode = "process",
                                                                log_level = "debug",
                                                                on_csv_write = "append")

Every time i try to run this cell, a new file named "test.csv_n.bak" (where n is the number of times i runned the cell) is created

### What I Did

```python
tracker = codecarbon.EmissionsTracker(output_dir = EMISSION_PATH+"/", 
                                    output_file = "test.csv",
                                    tracking_mode = "process",
                                    log_level = "debug",
                                    on_csv_write = "append")

tracker.start()

train_val_mnist = fit_and_eval(snet_mnist, epochs, optimizer, criterion, mnist_nclasses,
                                                  train_dataload_mnist, val_dataload_mnist, device, 
                                                  T=5, validation_step=True, convolution=False, onehot=False)

emissions_mnist_snn: float = tracker.stop()
```

**Comment by NicolaCST** [comment]
Just remove the initialization of the tracker from the cell.

**Comment by benoit-cty** [comment]
Did you solved your problem by initializing `EmissionsTracker` just one time ?
