### ISSUE TITLE
Visualization Tool: alignment and rounding

### ISSUE THREAD

**Issue by dkinneyBU** [mlco2/codecarbon#37]
For the metrics, Power Consumption... through Last Run Carbon.... the alignment is wonky. The first and third lines are left-justified, second and fourth are right-justified. Also, I'm thinking you could probably round these values somewhat?

![Screenshot from 2020-10-28 12-59-27](https://user-images.githubusercontent.com/43932354/97471235-e5cc0b00-191e-11eb-99bd-7eefdf228ab3.png)

**Comment by dkinneyBU** [comment]
Looks like maybe you did this on purpose???

html.Div(
                    [
                        html.H4(
                            [
                                "Power Consumption Across All Experiments : ",
                                html.Strong(
                                    id="project_power_consumption",
                                    style={"fontWeight": "normal", "color": "green"},
                                ),
                            ],
                            style={"float": "**left**"},
                        ),
                        html.H4(
                            [
                                "Last Run Power Consumption : ",
                                html.Strong(
                                    id="last_run_power_consumption",
                                    style={"fontWeight": "normal", "color": "green"},
                                ),
                            ],
                            style={"float": "**right**"},
                        ),
                    ]
                ),

**Comment by kngoyal** [comment]
Rounded to 1 decimal place, for initial runs users will probably see 0.0 if the values tend to be significantly low as in the example.

**Comment by kngoyal** [comment]
Re: alignment, I checked in my browser the alignment distorts when zoomed out at 25% and when zoomed in at 175%.
Alignment is perfect from 33% to 150%.
