### ISSUE TITLE
Feature request : being able to specify the TDP value

### ISSUE THREAD

**Issue by najeteb** [mlco2/codecarbon#376]
* CodeCarbon version: 2.1.4
* Python version: 3.8.10
* Operating System: Linux-5.4.0-1100-azure-x86_64-with-glibc2.29

### Description

When initializing the emission tracker in my Azure Databricks notebook, it notifies me during the CPU tracking set up that my CPU is unknown.

I read online that if CodeCarbon cannot find the appropriate software to track the CPUs' energy consumption, it will use a fallback strategy by using a constant TDP of 85W and assuming that the (average) actual power consumption of CPUs will be 50% of their TDP.

Wouldn't it be better if we were able to manually specify the TDP value when initializing the EmissionsTracker object when the CPU is unknown ?

Another question we had was : is CodeCarbon able to rigorously track the emissions when we're using Pyspark clusters ? 

### What I Did

Input :
```
from codecarbon import EmissionsTracker
tracker = EmissionsTracker()
```
Output :
```
[codecarbon INFO @ 14:37:08] [setup] RAM Tracking...
[codecarbon INFO @ 14:37:08] [setup] GPU Tracking...
[codecarbon INFO @ 14:37:08] No GPU found.
[codecarbon INFO @ 14:37:08] [setup] CPU Tracking...
[codecarbon WARNING @ 14:37:08] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 14:37:09] We saw that you have a Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz but we don't know it. Please contact us.
[codecarbon INFO @ 14:37:09] CPU Model on constant consumption mode: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
[codecarbon INFO @ 14:37:09] >>> Tracker's metadata:
[codecarbon INFO @ 14:37:09]   Platform system: Linux-5.4.0-1100-azure-x86_64-with-glibc2.29
[codecarbon INFO @ 14:37:09]   Python version: 3.8.10
[codecarbon INFO @ 14:37:09]   Available RAM : 22.473 GB
[codecarbon INFO @ 14:37:09]   CPU count: 8
[codecarbon INFO @ 14:37:09]   CPU model: Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
[codecarbon INFO @ 14:37:09]   GPU count: None
[codecarbon INFO @ 14:37:09]   GPU model: None
```

**Comment by SaboniAmine** [comment]
Hello,

We indeed assign a default value when cpu is not known. If you have the value of your target CPU (Intel(R) Xeon(R) Platinum 8171M if I correctly understood), you can open a PR to add it to our [list](https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/hardware/cpu_power.csv).
Regarding PySpark tracking, this is not supported by codecarbon at the moment. Indeed, the tracker might be initialized in the driver execution runtime, but won't be transmitted to remote executors to track emissions from each container spawned by Spark's internal scheduler. 
This is not something we are currently working on but any idea on how to integrate our tool to Spark might be welcome.
