### ISSUE TITLE
Experiment not visible on comet

### ISSUE THREAD

**Issue by kulkak2** [mlco2/codecarbon#380]
* CodeCarbon version: 2.1.4
* Python version: Python 3.6.8 (default, Jan 14 2022, 11:04:20)
* Operating System: Red Hat Enterprise Linux release 8.6 (Ootpa), 4.18.0-372.9.1.el8.x86_64

### Description
Trying to get co2 emissions of a node. Installed codecarbon and comet as described at https://www.comet.com/site/blog/introducing-codecarbon-an-open-source-tool-to-help-track-the-co2-emissions-of-your-research/

When I am running an experiment, and trying to see it in comet GUI, comet is not picking up my experiment. i.e. I can not see my experiment entry in the drop down list that is seen at the time of adding panel. 

It was expected that my experiment would show up while adding a panel for codecarbon. Can you please help with this issue ?

**Comment by benoit-cty** [comment]
Hello, @Lothiraldan (from Comet) Can you have a look ?

**Comment by benoit-cty** [comment]
Hello, @Lothiraldan  (from Comet) Can you have a look ?

**Comment by benoit-cty** [comment]
Closing for lack of support from Comet.
