### ISSUE TITLE
Ubuntu codecarbon: command not found

### ISSUE THREAD

**Issue by Xencemaaa** [mlco2/codecarbon#381]
* CodeCarbon version: Latest
* Python version: 3
* Operating System: Ubuntu

### Description

Hey, I'm trying to run codecarbon on my Ubuntu Virtual Machine. I have used 'pip install codecarbon' everything works but when I '! codecarbon init' or even 'codecarbon init' I get the error 'codecarbon: command not found'.
I have followed the same process on my Windows PC and it works just fine, any ideas?

**Comment by benoit-cty** [comment]
Hello, do you use virtualenv or venv ?
