### ISSUE TITLE
Documentation: bug in offline mode code example

### ISSUE THREAD

**Issue by tornede** [mlco2/codecarbon#392]
* CodeCarbon version: 2.1.4
* Python version: None
* Operating System: Documentation

### Description

Within the documentation, one [offline mode](https://mlco2.github.io/codecarbon/usage.html#offline-mode) code example for context manager imports the offline mode but uses the online mode. It has to be like: 

```python 
from codecarbon import OfflineEmissionsTracker

with OfflineEmissionsTracker() as tracker:
  # GPU intensive training code  goes here
```

Furthermore, the texts within this offline mode section should be checked to fit the offline mode.

### What I Did

Investigated the [offline mode](https://mlco2.github.io/codecarbon/usage.html#offline-mode) documentation ;)

**Comment by benoit-cty** [comment]
Thank you !
Note for the dev :
- Modify file https://github.com/mlco2/codecarbon/blob/master/docs/edit/usage.rst
- Rebuild the doc following https://github.com/mlco2/codecarbon/blob/master/CONTRIBUTING.md#build-documentation-%EF%B8%8F
