### ISSUE TITLE
Codecarbon keep running even when function fails

### ISSUE THREAD

**Issue by abhishekkrthakur** [mlco2/codecarbon#409]
* CodeCarbon version: 2.2.0
* Python version: 3.8.x
* Operating System: Ubuntu 22.04

As the title says. The function crashes but codecarbon keeps running. this is quite undesirable if codecarbon has to be used in a production environment. For example, a training ran for 3 days just because code carbon didnt shut down after function crash. Is it possible to fix it soon?

**Comment by benoit-cty** [comment]
Hello,
Can you share the way you call it ?
If you use the decorator it should work.
If you use tracker.start(), you have to do a tracker.stop() in the try/except.

**Comment by abhishekkrthakur** [comment]
yeah. not using decorator.

**Comment by benoit-cty** [comment]
The problem is that we use a scheduler and I don't know how to let it know that the main program has crashed without using the decorator.
