### ISSUE TITLE
Helping CodeCarbon 

### ISSUE THREAD

**Issue by markjohnsoncleanenergy** [mlco2/codecarbon#412]
Please tell me who I should work at CodeCarbon with on our nonprofit CleanEnergyBlockchain.com patent-pending digital cryptographic tracking, tracing, trading, auditing and retiring clean energy / carbon credits and our Northwestern University Master of Engineering Management team to identify AI datacenter peak demands for AI recommended energy efficiency best-practices and/or renewable energy microgrids like CleanestCharge.com to cut AI energy use paid for by both carbon credit trading and clean energy zero cost generation. Thanks in advance, MarkJohnson@CleanEnergyBlockchain.com

**Comment by inimaz** [comment]
Could you be more specific about how CodeCarbon can help you?

**Comment by inimaz** [comment]
Closing this, since no answer. Feel free to open it again if needed.
