### ISSUE TITLE
Account for the cost of cooling

### ISSUE THREAD

**Issue by roarin-roran** [mlco2/codecarbon#416]
### Description
it seems that the costs estimated are based on the direct energy usage of hardware but in data centers a significant fraction of the energy usage comes from cooling requirements.

are approaches to this mentioned anywhere I'm missing?

if not, this should probably be discussed and estimated

**Comment by benoit-cty** [comment]
Hello,
We just added in version 2.2.3 an option to set the datacenter PUE for that purpose : https://github.com/mlco2/codecarbon/blob/master/examples/pue.py

**Comment by roarin-roran** [comment]
fantastic! 

should this be documented here:
https://mlco2.github.io/codecarbon/parameters.html

seems to cover @track_emissions, but not the variables in the example.

also, how is this cooling cost estimated/measured? we're considering using code carbon for scientific purposes where we'll need to detail that.

**Comment by benoit-cty** [comment]
Hello, the PUE is a multiplication factor provided by the user, so it is up to the user to get it from his cloud provider.

Old data-centers have a PUE up to 2.2, where new green one coud be as low as 1.1.

I will update the documentation.
