### ISSUE TITLE
Doccumentation points to a broken link for global energy mix

### ISSUE THREAD

**Issue by roarin-roran** [mlco2/codecarbon#417]
* CodeCarbon version:
* Python version:
* Operating System:

### Description
when reading the documentation page on methodology:
https://mlco2.github.io/codecarbon/methodology.html

I clicked the link for global carbon intensity of electricity per country, and got a 404

the correct link seems to be this:
https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/private_infra/global_energy_mix.json

but I don't think I have the permissions to modify the doccumentation

in passing, it would be good to comment on CO2 eq on this page, and read through for consistency: total emissions are measured in terms of their CO2 equivelant, but the docs sometimes say that CO2 is measured.

**Comment by benoit-cty** [comment]
Thanks for reporting this.
