### ISSUE TITLE
Unable to track CPU for offline emissions 

### ISSUE THREAD

**Issue by huskyfire** [mlco2/codecarbon#418]
* CodeCarbon version: 2.2.3
* Python version: 3.8.13
* Operating System: Linux

Code Carbon is able to track GPU consumption but not CPU for offline emissions tracking,  CPU falls back on constant consumption mode, is there a way to fix this?

[codecarbon INFO @ 13:49:45] [setup] CPU Tracking...
[codecarbon WARNING @ 13:49:45] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 13:49:46] We saw that you have a Intel(R) Xeon(R) W-2275 CPU @ 3.30GHz but we don't know it. Please contact us.
[codecarbon INFO @ 13:49:46] CPU Model on constant consumption mode: Intel(R) Xeon(R) W-2275 CPU @ 3.30GHz
[codecarbon INFO @ 13:49:46]   CPU count: 28
[codecarbon INFO @ 13:49:46]   CPU model: Intel(R) Xeon(R) W-2275 CPU @ 3.30GHz
[codecarbon INFO @ 13:49:46]   GPU count: 2
[codecarbon INFO @ 13:49:46]   GPU model: 2 x NVIDIA GeForce RTX 3090
[codecarbon INFO @ 13:49:46] Energy consumed for RAM : 0.000000 kWh. RAM Power : 47.068817138671875 W
[codecarbon INFO @ 13:49:46] Energy consumed for all GPUs : 0.000000 kWh. Total GPU Power : 686.0880000000001 W
[codecarbon INFO @ 13:49:46] Energy consumed for all CPUs : 0.000000 kWh. Total CPU Power : 42.5 W

**Comment by inimaz** [comment]
Hi @huskyfire,
this is the expected behavior. Unfortunately, we do not know all CPU's TDP. 
We have a file containing all the TDPs [Link](https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/hardware/cpu_power.csv). 
If the CPU is not on the list, we go into constant mode. Maybe you could add yours TDP to that csv?

**Comment by huskyfire** [comment]
thank you. I have edited the csv locally but output is still constant. or do i have to reinstall the entire package?

**Comment by benoit-cty** [comment]
Hello, If you clone the project, you need to do 'pip install -e .' to install you local code.

I've made a commit to add it in the next release : https://github.com/mlco2/codecarbon/pull/422/files#diff-c249a89d94122afdb5bbd103eb2e54c63f74eb2fc01c69549ac861444406e33aR2130

**Comment by inimaz** [comment]
This should be solved by now, included in https://github.com/mlco2/codecarbon/releases/tag/v2.2.5
