### ISSUE TITLE
Error in documentation for output?

### ISSUE THREAD

**Issue by NickESouter** [mlco2/codecarbon#420]
### Description

On the 'output' page of the documentation (https://mlco2.github.io/codecarbon/output.html), energy use is described as being reported in kW. However, from my experience using CodeCarbon as it is integrated with fMRIPrep (https://fmriprep.org/en/stable/changes.html#december-12-2022) I believe that the output is actually report in kWh. Is it possible that this is an error in the documentation?

Thanks!

**Comment by LukasFehring** [comment]
Additionally,  in version  2.2.4 the metric pue is returned, but not explained in the output parameters

**Comment by benoit-cty** [comment]
You are right, indeed energy is in kWh and power in W.

Thanks for informing us of your usage, impressive project !

**Comment by LuisBlanche** [comment]
This was fixed by 9c5de172885a7bd36f3404ab8d5e483b817d3c4c
