### ISSUE TITLE
Errors in data manipulation of the `carbonboard`

### ISSUE THREAD

**Issue by EdAbati** [mlco2/codecarbon#423]
* CodeCarbon version: 2.2.4
* Python version: Python 3.10.12
* Operating System: MacOS 13.4.1 

### Description

I just discovered this very cool project, thank you for creating it! 🙂

I am currently testing `codecarbon` locally to see how it works, and I have noticed some possible bugs with the data manipulation in the local `carbonboard`.

### What I Did

- Created a very simple script that uses `EmissionsTracker` to track energy usage.
- Run `carbonboard --filepath="emissions.csv" --port=3333` to visualise the results

### Errors

These are some of the Exceptions that I saw in the Dash app logs:

```
  File "/[path]/miniconda3/envs/code-carbon-test/lib/python3.10/site-packages/codecarbon/core/emissions.py", line 228, in _global_energy_mix_to_emissions_rate
    energy_sum = energy_mix["total_TWh"]
KeyError: 'total_TWh'
```

```
  File "/[path]/miniconda3/envs/code-carbon-test/lib/python3.10/site-packages/codecarbon/viz/data.py", line 130, in get_global_emissions_choropleth_data
    global_energy_mix[country_iso_code]["fossil_TWh"], total
KeyError: 'fossil_TWh'
```

```
  File "/[path]/miniconda3/envs/code-carbon-test/lib/python3.10/site-packages/pandas/core/methods/to_dict.py", line 207, in to_dict
    raise ValueError(f"orient '{orient}' not understood")
ValueError: orient 'rows' not understood
```

### (Possible) Solutions

I have noticed that the keys/column names of the data used in the dashboard have changed in https://github.com/mlco2/codecarbon/pull/350/files#diff-729fd2eaf00d62e16106163521e91a169e8a24cf9d17250b5ff6bfc6cabafcda

The names affected should be updated and also the `orient="rows"` should be changed.

I will make a PR to solve this if you agree :)

**Comment by benoit-cty** [comment]
Thank you very much !
