### ISSUE TITLE
[Q] Does `codecarbon` add (significant) overhead?

### ISSUE THREAD

**Issue by NightMachinery** [mlco2/codecarbon#428]
I want to use `codecarbon` to measure the energy usage of my scripts. Does using `OfflineEmissionsTracker` add any overhead? If so, by how much?

Should `codecarbon` only be used on short, toy examples, or can we use it on the whole training loop?

**Comment by benoit-cty** [comment]
Hello,

CodeCarbon use a scheduler that, by default, call for the measure every 15 seconds so it has no significant overhead.
