### ISSUE TITLE
Power measurement interval

### ISSUE THREAD

**Issue by somas193** [mlco2/codecarbon#451]
* CodeCarbon version: 2.3.1
* Python version: 3.9.17
* Operating System: Windows 11 (WSL 2)

I use the `tracker.start_task()` and `tracker.stop_task()` functionality to track emissions for each iteration within a loop. I would like to know if the `measure_power_secs` parameter is retained as set in the `tracker` initialization or if a different value is used for `tracker.start_task()` and `tracker.stop_task()` methods?

**Comment by benoit-cty** [comment]
Hello,
When you call `tracker.start_task()`, the scheduler is stopped so `measure_power_secs` become useless.

**Comment by somas193** [comment]
Does that mean the power stats. are measured only when `tracker.start_task()` and `tracker.stop_task()` are called? There's no measurement in between?

**Comment by benoit-cty** [comment]
No, there's no measurement. We read energy counter from GPU and CPU so it is still accurate.
