### ISSUE TITLE
Incorrect use of the term 'Power'  in the Methodology webpage

### ISSUE THREAD

**Issue by jhowlett-scottlogic** [mlco2/codecarbon#455]
### Description

In the first code block in the Methodology page you state:
```
P = Power Consumed by the computational infrastructure: quantified as kilowatt-hours.
```

This is incorrect because kilowatt-hours are a unit of energy (1kWh = 3.6e+6J)

You use the term 'power' however that is the energy over time which is measured in watts.

watts and watt-hours are related as follows:

take a 60 watt (0.06 kilowatt) laptop charger. To get the total energy consumed by that charger you first get the duration that it is on charge, say 1 hour.

Then multiply together 0.06 kilowatts * 1 hour = 0.06 kilowatt-hours.

For your scenario you want to change your use of the word 'Power' with 'Energy' because you multiply the total energy (in kWh) by the carbon intensity of the electricty consumed (in gCO₂eq/kWh) to output the total carbon emissions (in gCO₂eq).

**Comment by benoit-cty** [comment]
Thanks for reporting this, I fix some mistakes in this page : https://github.com/mlco2/codecarbon/pull/456/files#diff-d4716f299c64e1ad38c68c4fbb5e0d11549ff71ec798c7a374bfc2a0e52de386
