### ISSUE TITLE
codecarbon as a server

### ISSUE THREAD

**Issue by dsblank** [mlco2/codecarbon#47]
Although I think that the emission tracker and dash website should be two different programs, since they are one, we should make it easy to use.

Currently the docs suggest that you need to have the source code to run the server:

```
python codecarbon/viz/carbonboard.py --filepath="./examples/emissions.csv"
```

But that isn't necessary. It is easier to:

```
python -m codecarbon.viz.carbonboard --filepath="./examples/emissions.csv"
```

But even that isn't that easy. We could easily make it do:

```
codecarbon --server --filepath="./examples/emissions.csv"
```

or at least

```
python -m codecarbon --server --filepath="./examples/emissions.csv"
```
Also, that gets rid of yet another name variation (carbonboard).

**Comment by dsblank** [comment]
Let me know if you want to do this. I think it would only take a change in the setup.py.

**Comment by kngoyal** [comment]
The dashboard can be opened with the cli command, refer [here](https://mlco2.github.io/codecarbon/visualize.html)

Needs package be installed.

**Comment by dsblank** [comment]
Thanks @kngoyal ! Then we need to:

* update README
* update examples

**Comment by kngoyal** [comment]
Updated README example
