### ISSUE TITLE
Does CodeCarbon track energy uses of popular APIs?

### ISSUE THREAD

**Issue by Dorado1987A** [mlco2/codecarbon#475]
* CodeCarbon version: 2.3.1
* Python version: 3.10.11
* Operating System: Windows-10-10.0.22621-SP0

### Description

Does CodeCarbon monitor energy use and emissions of APIs called?

For instance, if you call OpenAI's GPT model, CodeCarbon is only tracking the energy consumption of making the call and processing the API response rather than the consumption of the API side processing. Am I correct in that assumption?

If I wanted to add in consumption metrics for API calls and the related emission metrics, would this have to be a manual process I do rather than with CodeCarbon?

**Comment by SaboniAmine** [comment]
Hello,
Thanks for this feature request. We are currently opening this topic to study, to see if there is a viable methodology to estimate those values. The main issue is that it is difficult to guess which is the hardware used behind the APIs, thus its electrical consumption and the source of its energy. In any case this will first be done manually.
If you have any idea on how to measure this, please share it with us.

**Comment by SaboniAmine** [comment]
Thanks for your input, it is valuable.
We'll keep you updated about this topic, which is being addressed outside of this repo for the moment.

**Comment by benoit-cty** [comment]
Thanks @Dorado1987A , do you have a source for "OpenAI has published the energy consumption of each query sent to their various models via API" ? This will be very interesting.

**Comment by Dorado1987A** [comment]
Hi @benoit-cty, apparently, I was hallucinating that data. I swore I read a report with published data, but all I can find now is estimates... The below are the closest I've found to this type of insight - not much help, I know, sorry.

https://www.sciencedirect.com/science/article/pii/S2542435123003653

https://arxiv.org/pdf/2304.03271.pdf

**Comment by benoit-cty** [comment]
Thanks.
There's also Kasper Groes Albin Ludvigsen that has published some estimates: https://towardsdatascience.com/chatgpts-energy-use-per-query-9383b8654487

_Soon after ChatGPT’s debut in December, Altman estimated its cost to be “probably single-digits cents per chat.” multiplied it by the analysts’ anticipated upward of 10 million users each day. Based on the processing required to run GPT-3.5, the default model at the time, SemiAnalysis estimated in February that ChatGPT was costing OpenAI over $700,000 per day in computational expenditures alone._ [Source](https://lifeiztooshort.com/chatgpt-hidden-cost-gpu-compute/)

Another way is to use the production of Nvidia GPU as a basis:
_The paper includes a little more realistic scenario calculating the potential energy consumption of the 100,000 AI servers Nvidia is expected to deliver this year. Running at full capacity, those servers might burn through 5.7 to 8.9 TWh of electricity a year. That’s “almost negligible” in comparison to data centers’ historical estimated annual electricity use of 205 TWh, de Vries writes._ [TheVerge](https://www.theverge.com/2023/10/10/23911059/ai-climate-impact-google-openai-chatgpt-energy)

**Comment by benoit-cty** [comment]
There is a DataForGood France development in progress on this subject : https://dataforgood.fr/projects/genai-impacts

I think it's outside the scope of CodeCarbon do do API monitoring.

**Comment by adrien341** [comment]
Hi ! Sorry for re-openning this old topic, but has there been any change of thought concerning the monitoring of major APIs? 

To my current project, it would be rather useful being able to evaluate the cost of running gpt4o calls within a code, in addition to regular data science operations. 

I read the Data4goodFrance works you pointed out (thx btw !), and there seems to have a few academic works with orders of magitudes that CodeCarbon could integrate if needed. 

Anyway many thanks for your nice tool ! 

Ad.

**Comment by benoit-cty** [comment]
Hi Adrien,

The package https://ecologits.ai/latest/ has been released and does what you need.
