### ISSUE TITLE
Outdated link to conda repository 

### ISSUE THREAD

**Issue by fabian-sp** [mlco2/codecarbon#495]
The link in your docs to the conda repository (on https://mlco2.github.io/codecarbon/installation.html) is outdated. It points to

https://anaconda.org/codecarbon/codecarbon

**Comment by LuisBlanche** [comment]
Hello @fabian-sp thanks for using CodeCarbon. 

We will update the documentation soon , here is the real link : [https://anaconda.org/conda-forge/codecarbon](https://anaconda.org/conda-forge/codecarbon)

NB: We have an opened issue with a problem with the conda build  : #430
