### ISSUE TITLE
codecarbon not tracking CPU when RAPL data is available

### ISSUE THREAD

**Issue by mkbane** [mlco2/codecarbon#500]
* CodeCarbon version: 2.2.5
* Python version: 3.9.2
* Operating System:  Debian (Linux)

### Description

![image](https://github.com/mlco2/codecarbon/assets/90398937/ec52b100-ba7d-4acc-b88a-d2feed62be10)

so I can read RAPL but CC isn't tracking CPU

**Comment by benoit-cty** [comment]
Hello, I see you are using `CodeCarbon 2.2.5`, could you upgrade to the last version `2.3.4 ` ?

**Comment by mkbane** [comment]
Hi, sorry to re-open (been off ill but just tried).
Same issue with 2.3.4:
![image](https://github.com/mlco2/codecarbon/assets/90398937/4c08cb29-e0d4-4d2d-9790-f6b32123412d)

**Comment by mkbane** [comment]
I have tried to re-open…

**Comment by benoit-cty** [comment]
Thanks for reporting. I hope you are doing well.

Can you try with debug mode ?
```
export CODECARBON_LOG_LEVEL=DEBUG
codecarbon monitor
```
So we will see the exception in the log that prevent CodeCarbon from reading RAPL file.

**Comment by benoit-cty** [comment]
Hello, did you manage to activate debug ?

**Comment by benoit-cty** [comment]
Closed after more than one month without answer.
