### ISSUE TITLE
get the particular GPU energy

### ISSUE THREAD

**Issue by qxpBlog** [mlco2/codecarbon#509]
@dsblank @Lothiraldan @ndevenish @mp15 , soryy, i want to know when i set the variable gpu_ids as 1 in the file ~/.codecarbon.config, if this project only monitor and record the energy of GPU 1?

![image](https://github.com/mlco2/codecarbon/assets/96739096/ca70eb08-b371-4b79-84e4-17d041ff6cfe)

**Comment by benoit-cty** [comment]
Hello, yes, but the syntax is `1` not `[1]`

It will only monitor GPU 1 for GPU but keep measuring CPU and RAM.

**Comment by qxpBlog** [comment]
> Hello, yes, but the syntax is `1` not `[1]`
> 
> It will only monitor GPU 1 for GPU but keep measuring CPU and RAM.

thanks
