### ISSUE TITLE
Add output parameter

### ISSUE THREAD

**Issue by jevvyh** [mlco2/codecarbon#510]
* CodeCarbon version: 
* Python version: 3.11.5
* Operating System: macOS

### Description

I am trying to write a new variable that allows me to add the keywords of the project I am working on to the emissions.csv file after stopping tracker. I am unable to add anything to the script after tracker.stop. Would you be able to advice me on what is best to do to add a new variable to the output csv.

### What I Did

I have tried reading the emissions.csv file back in to edit after tracker.stop but the code stops running after tracker is stopped

**Comment by benoit-cty** [comment]
Hi, `tracker.stop()` is not supposed to stop the program. 
You could set a name when you instanciate the tracker with parameter `project_name`:

```py
tracker = EmissionsTracker(project_name="mnist_inference")
```

**Comment by benoit-cty** [comment]
Do you still have the problem ?

**Comment by inimaz** [comment]
Closing this. @jevvyh feel free to reopen it if you still have the problem.
