### ISSUE TITLE
how add new chipset

### ISSUE THREAD

**Issue by mkbane** [mlco2/codecarbon#524]
codecarbon WARNING @ 21:31:54] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 21:31:55] **We saw that you have a 13th Gen Intel(R) Core(TM) i9-13900 but we don't know it. Please contact us.**
[codecarbon INFO @ 21:31:55] CPU Model on constant consumption mode: 13th Gen Intel(R) Core(TM) i9-13900
[codecarbon INFO @ 21:31:55] >>> Tracker's metadata:
[codecarbon INFO @ 21:31:55]   Platform system: Linux-6.1.0-0.deb11.13-amd64-x86_64-with-glibc2.31
[codecarbon INFO @ 21:31:55]   Python version: 3.9.2
[codecarbon INFO @ 21:31:55]   CodeCarbon version: 2.3.4
[codecarbon INFO @ 21:31:55]   Available RAM : 125.504 GB
[codecarbon INFO @ 21:31:55]   CPU count: 32
[codecarbon INFO @ 21:31:55]   CPU model: 13th Gen Intel(R) Core(TM) i9-13900
[codecarbon INFO @ 21:31:55]   GPU count: 1
[codecarbon INFO @ 21:31:55]   GPU model: 1 x NVIDIA Graphics Device

what info is required so this chipset can be added?

I do have RAPL enabled. Turning on debug I get the following output:

codecarbon INFO @ 21:35:34] [setup] RAM Tracking...
[codecarbon INFO @ 21:35:34] [setup] GPU Tracking...
[codecarbon INFO @ 21:35:34] Tracking Nvidia GPU via pynvml
[codecarbon DEBUG @ 21:35:34] GPU available. Starting setup
[codecarbon INFO @ 21:35:34] [setup] CPU Tracking...
[codecarbon DEBUG @ 21:35:34] Not using PowerGadget, an exception occurred while instantiating IntelPowerGadget : Platform not supported by Intel Power Gadget
[codecarbon DEBUG @ 21:35:34] Not using the RAPL interface, an exception occurred while instantiating IntelRAPL : Unable to read Intel RAPL files for CPU power, we will use a constant for your CPU power. Please view https://github.com/mlco2/codecarbon/issues/244 for workarounds : [Errno 13] Permission denied: '/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj'
[codecarbon DEBUG @ 21:35:34] Not using PowerMetrics, an exception occurred while instantiating Powermetrics : Platform not supported by Powermetrics
[codecarbon WARNING @ 21:35:34] No CPU tracking mode found. Falling back on CPU constant mode.
[codecarbon WARNING @ 21:35:35] We saw that you have a 13th Gen Intel(R) Core(TM) i9-13900 but we don't know it. Please contact us.
[codecarbon INFO @ 21:35:35] CPU Model on constant consumption mode: 13th Gen Intel(R) Core(TM) i9-13900
[codecarbon INFO @ 21:35:35] >>> Tracker's metadata:
[codecarbon INFO @ 21:35:35]   Platform system: Linux-6.1.0-0.deb11.13-amd64-x86_64-with-glibc2.31
[codecarbon INFO @ 21:35:35]   Python version: 3.9.2
[codecarbon INFO @ 21:35:35]   CodeCarbon version: 2.3.4
[codecarbon INFO @ 21:35:35]   Available RAM : 125.504 GB
[codecarbon INFO @ 21:35:35]   CPU count: 32
[codecarbon INFO @ 21:35:35]   CPU model: 13th Gen Intel(R) Core(TM) i9-13900
[codecarbon INFO @ 21:35:35]   GPU count: 1
[codecarbon INFO @ 21:35:35]   GPU model: 1 x NVIDIA Graphics Device
[codecarbon DEBUG @ 21:35:36] Not running on AWS
[codecarbon DEBUG @ 21:35:37] Not running on Azure
[codecarbon DEBUG @ 21:35:38] Not running on GCP

**Comment by benoit-cty** [comment]
I'm closing this PR, don't hesitate to re-open if needed.
