### ISSUE TITLE
monitoring 3rd party code

### ISSUE THREAD

**Issue by cmeesters** [mlco2/codecarbon#543]
### Description

Thank you for this interesting project! I have been screening the docs, but could not find an example or description a use case of mine: how could we screen 3rd party processes started using `subprocess`?

**Comment by benoit-cty** [comment]
Hello, sorry you can't do that yet. CodeCarbon monitor the whole machine.

**Comment by cmeesters** [comment]
Ah, thank you. I subscribed to the mentioned PR.
