### ISSUE TITLE
Support for Intel(R) Xeon(R) Gold 6330N CPU @ 2.20GHz

### ISSUE THREAD

**Issue by CodingTomo** [mlco2/codecarbon#547]
* CodeCarbon version: 2.3.5
* Python version: 3.9.11
* Operating System: Ubuntu 22.04.2 LTS

### Description

Hi, 
I've been attempting to monitor the resource consumption of my models. I succeed on my local machine, but  not on my server. 
Upon reading the logger, it appears that the problem is that the library does not have support for Intel(R) Xeon(R) Gold 6330N CPU @ 2.20GHz  (please see the attached image).

Is it possible to add support for this CPU?

![Schermata del 2024-05-13 11-17-50](https://github.com/mlco2/codecarbon/assets/59206225/df5485c6-e55e-43f6-9842-4210ce836009)

**Comment by inimaz** [comment]
Hello @CodingTomo , thanks for using `codecarbon`!

We keep a database of the TDPs of several CPUs. I see that your CPU is included in the [latest release](https://github.com/mlco2/codecarbon/blob/master/codecarbon/data/hardware/cpu_power.csv#L3558). I see that you are using `codecarbon` version 2.3.5.  so please update to the last version of `codecarbon` (>=2.4.1), your CPU `Intel(R) Xeon(R) Gold 6330N` should be included in it .
Tell us if it is still not the case.

**Comment by CodingTomo** [comment]
Hello @inimaz, thank you for your answer.

I see I missed the latest update :)
However, I'm still encountering the same problem. Do you have any other suggestions?

![Schermata del 2024-05-13 14-18-33](https://github.com/mlco2/codecarbon/assets/59206225/1858e2e8-eb71-4f47-aaa0-f83c09cfd14a)

**Comment by benoit-cty** [comment]
Thanks for reporting this. We did have "Intel Xeon Gold 6330N" in the database so it means we have a bug with the fuzzy compare.

I did a PR to fix that : https://github.com/mlco2/codecarbon/pull/551
