### ISSUE TITLE
[unit tests] is_powermetrics_available stops the run to ask for `sudo`

### ISSUE THREAD

**Issue by inimaz** [mlco2/codecarbon#565]
I am using linux system. When I ran the unit tests, when it arrives to `test_powermetrics.py`, it asks for sudo permissions to run it.

```
tests/test_powermetrics.py::TestApplePowerMetrics::test_get_details [sudo] password for inigo: 
Sorry, try again.
[sudo] password for inigo: 
...
```
# How to reproduce
Run
`hatch run test:package`

**Comment by benoit-cty** [comment]
Thanks ! I'm having the same problem under Linux. But as it doesn't happened in CI I though it was a local problem.

**Comment by benoit-cty** [comment]
I think it's [this line](def _has_powermetrics_sudo():) that don't work as expected :    ` if re.search(r"[sudo].*password", stderr):`
