### ISSUE TITLE
Monitor other ML semiconductors besides GPUs

### ISSUE THREAD

**Issue by gaure** [mlco2/codecarbon#618]
Hi CodeCarbon Team

Thank you for creating this tool; it is precious for the IT industry.
I want to extend the CodeCarbon's code to add a new semiconductor.
I understand that I only need to create a new instance of the Semiconductor(BaseHardware) class and its respective semiconductor.py module;  is this correct?
Thanks in advance for any guidance you can provide me.
Best
GA

**Comment by benoit-cty** [comment]
Thanks !
Yes you could have a look at https://github.com/mlco2/codecarbon/blob/master/codecarbon/core/cpu.py
We also have GPU class, maybe it make less sense now that hybrid chips are coming.

**Comment by gaure** [comment]
Thank you @inimaz , I was caught in other issues and I couldn't see your response until now.thanks a lot for reply me back.

**Comment by inimaz** [comment]
Thanks to @benoit-cty ! Me I just tagged the issue
