### ISSUE TITLE
Print results into console on error

### ISSUE THREAD

**Issue by headscott** [mlco2/codecarbon#678]
* CodeCarbon version: 2.5.0
* Python version: 3.12.4
* Operating System: Linux-5.15.0-88-generic-x86_64-with-glibc2.35

### Description

Is it possible, to print all results into console if it crashes before it can put the results into the csv file? If it is not possible right now, could it be added?

### What I Did

I was just running a code for many hours, but it crashed after finishing the code, which I wanted to track due to an error while putting the results into the csv files.

**Comment by benoit-cty** [comment]
Hello,

You could do some things about it :
- use a try/finally : https://github.com/mlco2/codecarbon/issues/409#issuecomment-1562720863
- use flush() : https://github.com/mlco2/codecarbon/blob/480c7081dcc954250445ff363f4665b463f8c369/codecarbon/emissions_tracker.py#L598
- use the CodeCarbon API
- use a custom Output : https://github.com/mlco2/codecarbon/blob/480c7081dcc954250445ff363f4665b463f8c369/codecarbon/output_methods/file.py

**Comment by headscott** [comment]
Oh, okay thank you. I think this should work
