### ISSUE TITLE
[codecarbon WARNING @ 23:09:59] Another instance of codecarbon is already running. Exiting.

### ISSUE THREAD

**Issue by bashir-abubakar** [mlco2/codecarbon#702]
[codecarbon WARNING @ 23:09:59] Another instance of codecarbon is already running. Exiting.

How do i quit the instance? I have restarted my system but keep getting same error in juypter notebook using 

from codecarbon import EmissionsTracker
tracker = EmissionsTracker()

**Comment by inimaz** [comment]
Hi! 

Thanks for using `codecarbon`. There is a bug, that sometimes there is a hanging lock file that prevents from continuing.
Normally solved by https://github.com/mlco2/codecarbon/pull/701. This fix will be included in future releases. 

As a temporary workaround until the next release is ready you can find this lock file and remove it.
In Linux it should be 
```
rm /tmp/.codecarbon.lock
```

Sorry for the inconveniences

**Comment by inimaz** [comment]
@bashir-abubakar if you update the `codecarbon` package, the fix is included in the latest release (v2.7.4).
Feel free to test it and tell us if you still have the issue

**Comment by benoit-cty** [comment]
Closed by https://github.com/mlco2/codecarbon/pull/701

**Comment by raphischer** [comment]
The file will unfortunately not be removed if Python crashes fatally, for example due to a Segmenation Fault. Maybe it would make more sense to check for that file upon creating the tracker, remove it if exists, and print out a respective warning?
