### ISSUE TITLE
Change data format to JSON

### ISSUE THREAD

**Issue by vict0rsch** [mlco2/codecarbon#73]
This would allow the logging of individual hardware measurements:

```
[
	{
		"id": exp_id,
		"duration": ...,
		"emissions":{
						"hardware1": {
										"emissions": ...,
										"energy": ...,
									 },
						"hardware2": {...}
					},
		"region": region,
		...
	},
	{...},
	{...}
]
```

Thoughts @kngoyal @Lothiraldan ?

**Comment by vict0rsch** [comment]
This will require updates to the comet integration, dash app and comet panel so we might just aim for version 0.2

I can do the refactor, @kngoyal the Dash app, @Lothiraldan the comet integration and @dsblank the panel. 

Does that sound reasonable for you people? 

In the mean time we can define the json specs in this issue

**Comment by benoit-cty** [comment]
Does someone need this ?
