### ISSUE TITLE
Out-of-date RAM power consumption assumption

### ISSUE THREAD

**Issue by callmenoodles** [mlco2/codecarbon#751]
* CodeCarbon version: 2.8.0
* Python version: 3.12.7
* Operating System: Linux-6.12.1-arch1-1-x86 64-with-glibc2.40

### Description

In the documentation, under "RAM" in the "Power Usage" section, CodeCarbon states that it uses 3 W per 8 GB based on this source: https://www.crucial.com/support/articles-faq-memory/how-much-power-does-memory-use. However, the source recommends using 5 W per module.

### What I Did
I checked the page on the Wayback Machine, and if you go back to April 15, 2024, it shows that it recommends 3 W per 8 GB of DDR3 or DDR4 memory. The next entry on July 25, 2024 updated it, indicating they changed their recommendations anywhere between the aforementioned dates.

**Comment by benoit-cty** [comment]
Thanks, we will have a look to this in #717 . It means we have to find a way to count the number of module.

I will close this issue. Please comment in #717 if you want to add something else.
