### ISSUE TITLE
Invalid characters in RAPL test files for Windows

### ISSUE THREAD

**Issue by Lothiraldan** [mlco2/codecarbon#79]
* CodeCarbon version: master (05ae023177e9da9f3065212ad2270de80f486eac)
* Python version: 3.8.6
* Operating System: Windows 10

### Description

RAPL test files contains invalid characters for Windows (`:` colons), which trigger an error when trying to checkout the repository on windows:

```
$ git pull
error: invalid path `tests/test_data/rapl/intel-rapl:0/contraint_0_max_power_uw`
error: invalid path `tests/test_data/rapl/intel-rapl:0/contraint_0_name`
...
```

Could we remove those files and create them dynamically during the tests?

**Comment by kngoyal** [comment]
Fixed here https://github.com/mlco2/codecarbon/pull/80
