### ISSUE TITLE
Leave logging configuration to client programs

### ISSUE THREAD

**Issue by mdekstrand** [mlco2/codecarbon#87]
* CodeCarbon version: 1.0.0
* Python version: 3.8.6
* Operating System: Linux (with Anaconda)

### Description

I'm using CodeCarbon in a program that configures the Python logging infrastructure to provide output in my desired format.

CodeCarbon also configures Python logging, with `basicConfig`, on import. This results in duplicate logging configurations, so my program's logging setup is no longer respected and messages are duplicated (since both my handler and the basicConfig handler are printing them).

As a user of Python logging, I prefer that libraries allow me to configure logging myself, providing a hook if needed, rather than overriding logging configuration at import.

**Comment by vict0rsch** [comment]
Thank you for your feedback @mdekstrand I can understand that. 

Are you able to do a PR?

**Comment by Lothiraldan** [comment]
@mdekstrand How do you handle your logging configuration? Are you using the root logger or a named one? If we move the call to `basicConfig` from the module to the `EmissionTracker.__init__`, would your logging configuration already be in place?

**Comment by mdekstrand** [comment]
@Lothiraldan Yes, my config would already be in place by that time. I install my handler on the root logger, and put filters on a few different loggers (I would put filters on CodeCarbon and on the scheduler to keep the info messages from cluttering my output at all); all my own logging goes to various named loggers, but my scripts are designed to manage all logging (route to console, optionally route to log file, a context manager to route logging to a log file, etc.).

**Comment by LiamConnell** [comment]
This is being addressed in #103
