### ISSUE TITLE
Sweden ISO code incorrectly specified in global_energy_mix.json

### ISSUE THREAD

**Issue by acatovic** [mlco2/codecarbon#89]
* CodeCarbon version: 1.0.0
* Python version: 3.7.5
* Operating System: WSL (used under MS Windows 10)

### Description

Sweden ISO code should be "SWE" and not "SWI", lines 579 and 585 in data/private_infra/2016/global_energy_mix.json

### What I Did

from codecarbon import track_emissions
@track_emissions(offline=True, country_iso_code="SWE")

**Comment by Lothiraldan** [comment]
Thanks @acatovic for the bug report, we fixed it in https://github.com/mlco2/codecarbon/pull/88
