### ISSUE TITLE
Code fails silently when no hardware is detected

### ISSUE THREAD

**Issue by acatovic** [mlco2/codecarbon#90]
* CodeCarbon version: 1.0.0
* Python version: 3.7.5
* Operating System: WSL (used under MS Windows 10)

### Description

It seems when used under WSL, Intel Power Gadget and RAPL are not available. So you run the start()/stop() code and everything seems fine, but the emissions file is never written. There are probably lot of WSL users running jupyter notebooks and other DS/ML code under Windows in this way. It would be good to actually check that hardware is present.

It can easily be fixed in BaseEmissionsTracker class initialization code with the following:

if len(self._hardware) == 0:
    sys.exit("No hardware detected")

You need to import sys at the beginning, and you should place the above code after all your if/else checks on GPUs/CPUs.

### What I Did

from codecarbon import OfflineEmissionsTracker
tracker = OfflineEmissionsTracker(country_iso_code="CAN")
tracker.start()
# GPU intensive training code
tracker.stop()

**Comment by vict0rsch** [comment]
Thank you for your feedback @acatovic, we can look into this. @Lothiraldan or @kngoyal I don't have a Windows machine at hand do you?

In  the mean time, are you able to do a PR with what you'd like to see @acatovic ? That'd be great :)

**Comment by acatovic** [comment]
Absolutely @vict0rsch, will do, thanks!

**Comment by acatovic** [comment]
@vict0rsch I think you need to grant me access (or push privileges), otherwise I can't push my own branch and do a PR. Thanks!

**Comment by vict0rsch** [comment]
@acatovic Can you do that from a fork? If that is somehow a problem I will but I think it is better practice :)

**Comment by Lothiraldan** [comment]
@acatovic I can understand that the behavior is not what you expected. We will likely have some environment where we don't have access to any hardware related metrics to compute the emission. In addition, in a team some users might run the same code (with code-carbon code) on both environments that are supported and environments that are not.

If we would expose an helper function indicating if we have any supported hardware metrics, would that works for you? Something like:

```
if not code_carbon.has_supported_sources():
    sys.exit(1)
```

**Comment by acatovic** [comment]
@vict0rsch absolutely, i did a fork, code change and PR has now been submitted.

@Lothiraldan sounds good! I did a PR you can have a look - instead of sys.exit(1) I opted to simply raise a ValueError - this way you can do the usual exception handling and allow for seamless continuation of code in those instances where you "know" that sometimes you will run into this situation. Much nice than forcing a program exit. And for the rest of us (like myself :-) ) that were caught a bit off guard, you get an exception, and then you move onto a real machine to do the work ;-)

**Comment by kngoyal** [comment]
@acatovic We would not like codecarbon to fail the user code, in case no hardware is detected.
