### ISSUE TITLE
Expose more emissions statistics in API

### ISSUE THREAD

**Issue by mdekstrand** [mlco2/codecarbon#94]
* CodeCarbon version: 1.0
* Python version: 3.8
* Operating System: <any>

### Description

I would love to easily be able to get the kWh, not just the kG, in my code when calling `EmissionsTracker`. This is likely a backwards-incompatible change, but given that I'm not at all sure CodeCarbon has my building's power mix cost correct, I'm love to be able to log kWh, or to have access to any of CodeCarbon's statistics, when shutting down the tracker. I can get the data out of `emissions.csv`, but `stop()` just returns the kG of carbon, and the full energy consumption / emissions statistics aren't stored in a field or anything I can programmatically access.

Just an idea. But it would make things a little easier for how I'm looking at integrating CodeCarbon into my workflows.

**Comment by vict0rsch** [comment]
Thanks for the feedback @mdekstrand and sorry it took us 6months to get back to you we missed your issue. 

Would you be keen on contributing with us to codecarbon so that it fits your use-case?

**Comment by benoit-cty** [comment]
Hello @mdekstrand , we have done it in https://github.com/mlco2/codecarbon/pull/210
